In [ ]:
# Layers API overview

'''
Layer activations
    1. relu function : Rectified Linear Activation Function 
    2. Sigmoid 
    3. Softmax
    4. Softplus
    5. Softsign
    6. Tanh : Hyperbolic tangent activation function
    7. selu : Scaled Exponential Linear Unit 
    8. elu  : Exponential Linear Unit
    9. gelu : Gaussian error linear unit (GELU)
    10.hard_sigmoid
    11.linear
    13.Exponential
'''

In [ ]:
'''
Layer Weight Initilizer
    1. RandomNormal class
    2. RandomUniform class
    3. TruncatedNormal class
    4. Zeros class
    5. Ones class
    6. GlorotNormal class
    7. GlorotUniform class
    8. Identity class
    9. Orthogonal class
    10. Constant class
    11. VarianceScaling class
'''

In [ ]:
'''
Layer weight regularizers
    1. l1 class
    2. l2 class
    3. l1_l2 class

'''

In [ ]:
'''
# Layer weight constraints
    1. MaxNorm class
    2. MinMaxNorm class
    3. NonNeg class
    4. UnitNorm class
    5. RadialConstraint class
    
'''
# Constraints module allow setting constraints(ex>Non-Negativity) on model parameters during traing

In [ ]:
'''
Core layers
    1. Input object
    2. Dense layer
    3. Activation layer
    4. Embedding layer
    5. Masking layer
    6. Lambda layer
'''

In [ ]:
'''
Convolution layers
    1.Conv1D layer
    2.Conv2D layer
    3.Conv3D layer
    4.SeparableConv1D layer
    5.SeparableConv2D layer
    6.DepthwiseConv2D layer
    7.Conv2DTranspose layer
    8.Conv3DTranspose layer
'''

In [ ]:
'''
Pooling layers
    1. MaxPooling1D layer
    2. MaxPooling2D layer
    3. MaxPooling3D layer
    4. AveragePooling1D layer
    5. AveragePooling2D layer
    6. AveragePooling3D layer
    7. GlobalMaxPooling1D layer
    8. GlobalMaxPooling2D layer
    9. GlobalMaxPooling3D layer
    10. GlobalAveragePooling1D layer
    11. GlobalAveragePooling2D layer
    12. GlobalAveragePooling3D layer
'''

In [ ]:
'''
Recurrent layers

    1. LSTM layer
    2. GRU layer
    3. SimpleRNN layer
    4. TimeDistributed layer
    5. Bidirectional layer
    6. ConvLSTM2D layer
    7. Base RNN layer
'''

In [ ]:
'''
Normalization layers
    1. BatchNormalization layer
    2. LayerNormalization layer

'''

In [ ]:
'''
Regularization layers
    1. Dropout layer
    2. SpatialDropout1D layer
    3. SpatialDropout2D layer
    4. SpatialDropout3D layer
    5. GaussianDropout layer
    6. GaussianNoise layer
    7. ActivityRegularization layer
    8.AlphaDropout layer
'''

In [ ]:
'''
Reshaping layers
    1. Reshape layer
    2. Flatten layer
    3. RepeatVector layer
    4. Permute layer
    5. Cropping1D layer
    6. Cropping2D layer
    7. Cropping3D layer
    8. UpSampling1D layer
    9. UpSampling2D layer
    10.UpSampling3D layer
    11. ZeroPadding1D layer
    12. ZeroPadding2D layer
    13.ZeroPadding3D layer
'''

In [ ]:
'''
Merging layers
    1. Concatenate layer
    2. Average layer
    3. Maximum layer
    4. Minimum layer
    5. Add layer
    6. Subtract layer
    8. Multiply layer
    9. Dot layer

'''

In [ ]:
'''
Locally-connected layers
    1. LocallyConnected1D layer
    2. LocallyConnected2D layer
'''

In [ ]:
'''
Optimizers 
    1. Adadelta : Extension of Adagrad : Adadelta(adaptive delta)
    2. Adagrad  : Adaptive Gradient Algorithm
    3. Adam     : Adaptive Moment Estimation
    4. Adamax   :
    5. Ftrl     : Follow The Regularized Leader
    6. Nadam    : Nesterov-accelerated Adaptive Moment Estimation
    7. RMSprop  : Root Mean Square Propagation 
    8. SGD      : Stochastic Gradient Descent
'''

In [ ]:
'''
Loss Functions
    1. mean_squared_error
    2. mean_absolute_error
    3. mean_absolute_percentage_error
    4. mean_squared_logarithmic_error
    5. squared_hinge
    6. hinge
    7. categorical_hinge
    8. logcosh
    9. huber_loss
    10. categorical_crossentropy
    11. sparse_categorical_crossentropy
    12. binary_crossentropy
    13. kullback_leibler_divergence
    14. poisson
    15. cosine_proximity
    16. is_categorical_crossentropy
'''

In [ ]:
'''
Metrics
    1. AUC : Area Under Curve
    2. Accuracy
    3. Binary Accuracy
    4. BinaryCrossEntropy
    5. CategoricalAccuracy
    6. CategoricalCrossEntropy
    7. CategoricalHinge
    8. CosineSimilarity
    9. FalseNegative
    10. FalsePositive
    11. Hinge
    12. KLDivergence
    13. LogCoshError
    14. Mean
    15. MeanAbolsuteError
    16. MeanAbsolutePercentageError
    17. MeanIou
    18. MeanRelatievError
    19. MeanSqaredError
    20. MeanSquaredLogarithmicError
    21. MeanTensor
    22. Poission
    23. PrecisionAtRecall
    24. Recall
    25. RecallAtPrecision
    26. RootMeanSquaredError
    27. SensitivityAtSpecificity
    28. SparseCatgoricalAccuracy
    29. SparseTopKCategoricalAccuracy
    30.SpecificityAtSensivity
    31.SquardHinge
    32. Sum
    33. TopKCategoricalAccuracy
    34. TrueNegative
    35 TruePositives
'''

In [ ]:
import tensorflow as tf
tf.enable_eager_execution()

In [63]:
# Input : input is used to instantiate a Keras tensor.

from tensorflow.keras import Input

inputs = Input(shape=(3,))
print(inputs) # 2D

inputs = Input(shape=(3,4))
print(inputs) # 3D

Tensor("input_3:0", shape=(?, 3), dtype=float32)
Tensor("input_4:0", shape=(?, 3, 4), dtype=float32)


In [ ]:
# ****Activation Function*********

In [ ]:
# linear

In [76]:
# Sigmoid :  1 / (1 + exp(-x))

a = tf.constant([-20, -1.0, 0.0, 1.0, 20], dtype = tf.float32)

tf.keras.activations.sigmoid(a).numpy()

array([0.        , 0.26894143, 0.5       , 0.7310586 , 1.        ],
      dtype=float32)

In [65]:
# relu function : Degault if x<0 consider as value as 0

foo = tf.constant([-10, -5, 0.0, 5, 10], dtype = tf.float32) 
# Default : tf.keras.activations.relu(x, alpha=0.0, max_value=None, threshold=0)

tf.keras.activations.relu(foo).numpy()

array([ 0.,  0.,  0.,  5., 10.], dtype=float32)

In [67]:
# relu function : alpha ; if value is lessthan zero means values/0.5

tf.keras.activations.relu(foo, alpha=0.5).numpy()

array([-5. , -2.5,  0. ,  5. , 10. ], dtype=float32)

In [68]:
# relu function : max_value
tf.keras.activations.relu(foo, max_value=5).numpy()

array([0., 0., 0., 5., 5.], dtype=float32)

In [70]:
# relu function : threshold
tf.keras.activations.relu(foo, threshold=5).numpy()

array([-0., -0.,  0.,  0., 10.], dtype=float32)

In [83]:
inputs
from tensorflow.keras import layers

layer = layers.Dense(4, activation='relu')

inputs = tf.convert_to_tensor([[-1,4,5,3],[1,6,0.3,1]])

outputs = layer(inputs)

outputs

<tf.Tensor: id=465, shape=(2, 4), dtype=float32, numpy=
array([[1.4945302 , 0.6327658 , 0.        , 0.12925196],
       [0.43063554, 0.        , 0.        , 0.        ]], dtype=float32)>

In [115]:
# Softmax : 

inp = np.asarray([1., 2., 1.])
layer = tf.keras.layers.Softmax()
layer(inp).numpy()

array([0.21194156, 0.57611688, 0.21194156])

In [82]:
# Softplus : log(exp(x) + 1)
a = tf.constant([-20, -1.0, 0.0, 1.0, 20], dtype = tf.float32)
tf.keras.activations.softplus(a).numpy()

array([2.0611537e-09, 3.1326166e-01, 6.9314718e-01, 1.3132616e+00,
       2.0000000e+01], dtype=float32)

In [80]:
# Softsign : x / (abs(x) + 1)

a = tf.constant([-1.0, 0.0, 1.0], dtype = tf.float32)
tf.keras.activations.softsign(a).numpy()

array([-0.5,  0. ,  0.5], dtype=float32)

In [77]:
# Tanh : Hyperbolic tangent activation function
# tanh : sinh(x)/cosh(x) = ((exp(x) - exp(-x))/(exp(x) + exp(-x))).

a = tf.constant([-3.0,-1.0, 0.0,1.0,3.0], dtype = tf.float32)
tf.keras.activations.tanh(a).numpy()


array([-0.9950547, -0.7615942,  0.       ,  0.7615942,  0.9950547],
      dtype=float32)

In [ ]:
# selu : Scaled Exponential Linear Unit 
# if x > 0: return scale * x
# if x < 0: return scale * alpha * (exp(x) - 1)
# constants (alpha=1.67326324 and scale=1.05070098)


In [ ]:
# gelu : Gaussian error linear unit (GELU)

In [ ]:
# hard_sigmoid

In [79]:
# Exponential : exp(x).

a = tf.constant([-3.0,-1.0, 0.0,1.0,3.0], dtype = tf.float32)

tf.keras.activations.exponential(a).numpy()

array([ 0.04978707,  0.36787945,  1.        ,  2.7182817 , 20.085537  ],
      dtype=float32)

In [ ]:
# ELU :  Exponential Linear Unit 

# f(x) = x for x >= 0
# f(x) =  alpha * (exp(x) - 1.) for x < 0


In [ ]:
# **** Layer Weight Initilizer

# Weights Initializer
    1. kernel_initializer
    2. bias_initializer 

from tensorflow.keras import initializers

# Example : Weights Initializer
model.add(layers.Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = my_init))

# Normal Value
kernel_initializer = "normal"

# Zero Values
kernel_initializer = initializers.Zeros() 

# Ones Values
kernel_initializer = initializers.Ones() 

# Constant values
kernel_initializer = initializers.Constant(value = 5) 

# Random Normal
kernel_initializer = initializers.RandomNormal(mean=0.0, stddev = 0.05, seed = None) 

# Random Uniform
kernel_initializer = initializers.RandomUniform(minval = -0.05, maxval = 0.05, seed = None)

# Truncated Normal
kernel_initializer = initializers.TruncatedNormal(mean = 0.0, stddev = 0.05, seed = None)

#Variance Scaling
kernel_initializer = initializers.VarianceScaling(scale = 1.0, mode = 'fan_in', distribution = 'normal', seed = None) 

#lecun_normal
kernel_initializer = initializers.RandomUniform(minval = -0.05, maxval = 0.05, seed = None) 

# lecun_uniform
kernel_initializer = initializers.lecun_uniform(seed = None) 

# glorot_normal
kernel_initializer = initializers.glorot_normal(seed=None) 

# Identitty  : Initializer that generates the identity matrix.
kernel_initializer = tf.keras.initializers.Identity(gain=1.0)

# Orthogonal : nitializer that generates an orthogonal matrix.
kernel_initializer = tf.keras.initializers.Orthogonal(gain=1.0, seed=None)


In [ ]:
# Regularizer
    1. kernel_regularizer (Dense)
    2. bias_regularizer  (Convolutional)
    3. recurrent_regularizer (LSTM)

from tensorflow.keras import regularizers

# Example : Regularizer 
model.add(layers.Dense(512,activation='relu',input_shape=(784,),kernel_regularizer=my_regularizer))

# L2 Regularize
my_regularizer = regularizers.L1(0.)

# L2 Regularize
my_regularizer = regularizers.L2(0.)

#L1 and L2 Regularize
my_regularizer = regularizers.L1L2(0.0,0.0)

# Weight Regularization for Convolutional Layers
model.add(Conv2D(32, (3,3), kernel_regularizer=regularizers.l2(0.01), bias_regularizer=regularizers.l2(0.01)))

# Bias _Regularizers
bias_regularizer=l2(0.01)

# Bias _Regularizers
bias_regularizer=l2(0.01)

# Weight Regularization for Recurrent Layers
model.add(LSTM(32, kernel_regularizer=l2(0.01), recurrent_regularizer=regularizers.l2(0.01),
                   bias_regularizer=regularizersl2(0.01)))

# Recurrent Regularization for LSTM
recurrent_regularizer=l2(0.01)

In [ ]:
# Layer Weight constraints
# Weight constraints provide an approach to reduce the overfitting of a deep learning.

model.add(Dense(32, kernel_constraint=max_norm(3), bias_constraint=max_norm(3))) # Dense
model.add(Conv2D(32, (3,3), kernel_constraint=max_norm(3), bias_constraint=max_norm(3))) # CNN
model.add(LSTM(32, kernel_constraint=max_norm(3), recurrent_constraint=max_norm(3), bias_constraint=max_norm(3))) # LSTM

# MaxNorm : Weights incident to each hidden unit to have a norm less than or equal to a desired value
tf.keras.constraints.MaxNorm(max_value=2, axis=0)

# MinMaxNorm: Constrains the weights incident to each hidden unit to have the norm between a lower bound and an upper bound.
tf.keras.constraints.MinMaxNorm(min_value=0.0, max_value=1.0, rate=1.0, axis=0)

# NonNeg : Constrains the weights to be non-negative

# RadialConstraint: Constrains Conv2D kernel weights to be the same for each radius.

# unitNorm : Constrains the weights incident to each hidden unit to have unit norm.
tf.keras.constraints.UnitNorm(axis=0)


In [ ]:
# Model : Model groups layers into an object with training and inference features.

import tensorflow as tf

# Define Input:
inputs = tf.keras.Input(shape=(3,))

# Define output
outputs = tf.keras.layers.Dense(2)(inputs)

model = tf.keras.models.Model(inputs=inputs, outputs=outputs)

model.compile(optimizer="Adam", loss="mse", metrics=["mae"])
model.metrics_names

In [ ]:
inputs = tf.keras.layers.Input(shape=(3,))
    
d = tf.keras.layers.Dense(2, name='out')

output_1 = d(inputs)
output_2 = d(inputs)

model = tf.keras.models.Model(inputs=inputs, outputs=[output_1, output_2])
model.compile(optimizer="Adam", loss="mse", metrics=["mae", "acc"])

import numpy as np
x = np.random.random((2, 3))
y = np.random.randint(0, 2, (2, 2))

model.fit(x, (y, y))

In [ ]:
model = Sequential()
model.add(Dense(16, input_dim=13, kernel_initializer="normal",activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(1, kernel_initializer="normal"))

model.compile(loss="mean_squared_error", optimizer="adam")

In [ ]:
# Define Input

input_dim=13
input_shape = (13,)

In [89]:
# tf.keras.layers.Add

# Layer that adds a list of inputs.
# It takes as input a list of tensors, all of the same shape, and returns a single tensor 

input_shape = (2,3, 4)

x1 = tf.random.normal(input_shape)
x2 = tf.random.normal(input_shape)

y = tf.keras.layers.Add()([x1, x2])

print(x1)

tf.Tensor(
[[[-0.24116312  1.3015687   0.7565762  -0.47319087]
  [ 0.97014725  0.28704515 -0.25953227 -0.6662777 ]
  [-1.368204    2.3441765  -2.0411115   0.38773426]]

 [[-0.1476079  -0.5302426   0.43511036  0.13674329]
  [ 1.172246    0.40507308  1.06943     0.4349389 ]
  [ 0.08766053 -1.7162492  -0.6831919  -0.7756794 ]]], shape=(2, 3, 4), dtype=float32)


In [90]:
# using Functional API implementing Add Function

input1 = tf.keras.layers.Input(shape=(16,))
x1 = tf.keras.layers.Dense(8, activation='relu')(input1)

input2 = tf.keras.layers.Input(shape=(32,))
x2 = tf.keras.layers.Dense(8, activation='relu')(input2)

added = tf.keras.layers.Add()([x1, x2])

out = tf.keras.layers.Dense(4)(added)

model = tf.keras.models.Model(inputs=[input1, input2], outputs=out)

In [95]:
# tf.keras.layers.Average : Layer that averages a list of inputs element-wise.

input1 = tf.keras.layers.Input(shape=(16,))
x1 = tf.keras.layers.Dense(8, activation='relu')(input1)

input2 = tf.keras.layers.Input(shape=(32,))
x2 = tf.keras.layers.Dense(8, activation='relu')(input2)

avg = tf.keras.layers.Average()([x1, x2])

out = tf.keras.layers.Dense(4)(avg)

model = tf.keras.models.Model(inputs=[input1, input2], outputs=out)

In [ ]:
# Bathc Normalization :

# Batch normalization is a technique for training very deep neural networks that standardizes the inputs to a layer for 
# each mini-batch.This has the effect of stabilizing the learning process and dramatically reducing the 
# number of training epochs required to train deep networks.

# Batch normalization applies a transformation that maintains the mean output close to 0 and the output standard deviation close to 1.


In [105]:
# Concatenate

# Layer that concatenates a list of inputs.

x1 = tf.keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
x2 = tf.keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))

concatted = tf.keras.layers.Concatenate()([x1, x2])


In [106]:
# Dot

x = np.arange(10).reshape(1, 5, 2)
y = np.arange(10, 20).reshape(1, 2, 5)

tf.keras.layers.Dot(axes=(1, 2))([x, y])

<tf.Tensor: id=854, shape=(1, 2, 2), dtype=int32, numpy=
array([[[260, 360],
        [320, 445]]])>

In [114]:
# Dropout

# The Dropout layer randomly sets input units to 0 with a frequency of rate at each step during training time,
# which helps prevent overfitting

data = np.arange(10).reshape(5, 2).astype(np.float32)

layer = tf.keras.layers.Dropout(.2, input_shape=(2,))

print(data)

outputs = layer(data, training=True)

print("\n")
print('After Dropout:')

print(outputs)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


After Dropout:
tf.Tensor(
[[ 0.    1.25]
 [ 2.5   3.75]
 [ 5.    0.  ]
 [ 0.    8.75]
 [10.    0.  ]], shape=(5, 2), dtype=float32)


In [116]:
# maximum

# Functional interface to compute maximum (element-wise) list of inputs.

input1 = tf.keras.layers.Input(shape=(16,))
x1 = tf.keras.layers.Dense(8, activation='relu')(input1) #shape=(None, 8)

input2 = tf.keras.layers.Input(shape=(32,))
x2 = tf.keras.layers.Dense(8, activation='relu')(input2) #shape=(None, 8)

max_inp=tf.keras.layers.maximum([x1,x2]) #shape=(None, 8)

out = tf.keras.layers.Dense(4)(max_inp)

In [128]:
# maximum

inout1 = tf.convert_to_tensor([[1,2,9],[4,11,6]])
inout2 = tf.convert_to_tensor([[7,8,9],[10,11,12]])

tf.keras.layers.maximum([inout1,inout2]) #shape=(None, 8)

<tf.Tensor: id=1037, shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [133]:
# Minimum : Layer that computes the minimum (element-wise) a list of inputs.

inout1 = tf.convert_to_tensor([[1,2,9],[4,11,6]])
inout2 = tf.convert_to_tensor([[7,8,9],[10,11,12]])

tf.keras.layers.minimum([inout1,inout2]) #shape=(None, 8)

<tf.Tensor: id=1042, shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  9],
       [ 4, 11,  6]])>

In [ ]:
# Minimum

x1 = tf.keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
x2 = tf.keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))

minned = tf.keras.layers.Minimum()([x1, x2])

In [143]:
# Multiply : Layer that multiplies (element-wise) a list of inputs.

inout1 = tf.convert_to_tensor([[1,2,9],[4,11,6]])
inout2 = tf.convert_to_tensor([[7,8,9],[10,11,12]])

tf.keras.layers.multiply([inout1,inout2]) #shape=(None, 8)

<tf.Tensor: id=1049, shape=(2, 3), dtype=int32, numpy=
array([[  7,  16,  81],
       [ 40, 121,  72]])>

In [ ]:
# Multiply :

x1 = tf.keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
x2 = tf.keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))

multiplied = tf.keras.layers.Multiply()([x1, x2])

In [ ]:
# Subtract : Layer that Subtract (element-wise) a list of inputs.

inout1 = tf.convert_to_tensor([[1,2,9],[4,11,6]])
inout2 = tf.convert_to_tensor([[7,8,9],[10,11,12]])

tf.keras.layers.Subtract([inout1,inout2]) #shape=(None, 8)

In [176]:
# RepeatVector: Repeats the input n times.

import tensorflow as tf

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(32, input_dim=8))

# add RepeatVector
print('Before RepeatVector')
print(model.output_shape)

model.add(tf.keras.layers.RepeatVector(3))

print('After RepeatVector')
print(model.output_shape)

Before RepeatVector
(None, 32)
After RepeatVector
(None, 3, 32)


In [188]:
# Reshape : Layer that reshapes inputs into the given shape.

model = tf.keras.Sequential()
model.add(tf.keras.layers.Reshape((3, 4), input_shape=(12,)))

print(model.output_shape)

model.add(tf.keras.layers.Reshape((6, 2)))

print(model.output_shape)

model.add(tf.keras.layers.Reshape((-1, 2, 2)))

print(model.output_shape)

(None, 3, 4)
(None, 6, 2)
(None, None, 2, 2)


In [195]:
# Average

x1 = np.ones((2, 2))
x2 = np.zeros((2, 2))

y = tf.keras.layers.Average()([x1, x2])

y.numpy().tolist()

[[0.5, 0.5], [0.5, 0.5]]

In [132]:
# Flattern : Flattens the input. Does not affect the batch size.



In [ ]:
# Optimizers 

# Adadelta : Extension of Adagrad : Adadelta(adaptive delta)
# Adagrad  : Adaptive Gradient Algorithm
# Adam     : Adaptive Moment Estimation
# Adamax   :
# Ftrl     : Follow The Regularized Leader
# Nadam    : Nesterov-accelerated Adaptive Moment Estimation
# RMSprop  : Root Mean Square Propagation 
# SGD      : Stochastic Gradient Descent

from tensorflow.keras import optimizers

from tensorflow.keras.optimizers import Adadelta
adadelta = Adadelta(learning_rate=0.001, rho=0.95, epsilon=1e-07, name='Adadelta',**kwargs)
# Adadelta
model.compile(optimizer='adadelta',loss='categorical_crossentropy',metrics=['accuracy'])

from tensorflow.keras.optimizers import Adagrad
adagrad = Adagrad(learning_rate=0.001,initial_accumulator_value=0.1,epsilon=1e-07,name="Adagrad",**kwargs) 
# Adagrad
model.compile(optimizer='adagrad',loss='categorical_crossentropy',metrics=['accuracy'])

from tensorflow.keras.optimizers import Adam
#Adam
adam = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False,name='Adam', **kwargs) 
model.compile(optimizer=adam,loss='categorical_crossentropy',metrics=['accuracy'])

from tensorflow.keras.optimizers import Adamax
# AdaAmx
adamax = Adamax(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07,name='Adamax', **kwargs) 
model.compile(optimizer=adamax,loss='categorical_crossentropy',metrics=['accuracy'])

from tensorflow.keras.optimizers import Ftrl
# Ftrl
ftrl = Ftrl(learning_rate=0.001,learning_rate_power=-0.5,initial_accumulator_value=0.1,l1_regularization_strength=0.0,
            l2_regularization_strength=0.0,name="Ftrl",l2_shrinkage_regularization_strength=0.0,beta=0.0,**kwargs)
model.compile(optimizer=ftrl,loss='categorical_crossentropy',metrics=['accuracy'])

from tensorflow.keras.optimizers import Nadam
# Nadam
nadam = Nadam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07,name='Nadam', **kwargs) 
model.compile(optimizer=nadam,loss='categorical_crossentropy',metrics=['accuracy'])

from tensorflow.keras.optimizers import RMSprop
# RMSProp
rmsprop = RMSprop(learning_rate=0.001,rho=0.9, momentum=0.0, epsilon=1e-07, 
                  centered=False,name='RMSprop', **kwargs) 
model.compile(optimizer=rmsprop,loss='categorical_crossentropy',metrics=['accuracy'])

from tensorflow.keras.optimizers import SGD
# SGD
sgd = SGD(lr =0.01,decay=1e-6, momentum=0.9, nesterov=True)
model.compile(optimizer=sgd,loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
# Loss functions

#1. mean_squared_error
#2. mean_absolute_error
#3. mean_absolute_percentage_error
#4. mean_squared_logarithmic_error
#5. squared_hinge
#6. hinge
#7. categorical_hinge
#8. logcosh
#9. huber_loss
#10. categorical_crossentropy
#11. sparse_categorical_crossentropy
#12. binary_crossentropy
#13. kullback_leibler_divergence
#14. poisson
#15. cosine_proximity
#16. is_categorical_crossentropy


- Regression
    - mean_squared_error
    - mean_absolute_error
    - mean_absolute_percentage_error
    - mean_squared_logarithmic_error
    - cosine_proximity
    - huber_loss
    - logcosh
- Binary and Multi Classification
    - binary_crossentropy
    - categorical_crossentropy
    - poisson loss
    - sparse_categorical_crossentropy
    - kullback_leibler_divergence
- Hinge losses 
    - Hinge
    - Categorical Hinge
    - Squared Hinge

In [84]:
# Metrics

from keras import metrics

metrics.BinaryCrossentropy

# AUC : Area Under Curve
# Accuracy
# Binary Accuracy
# BinaryCrossEntropy
# CategoricalAccuracy
# CategoricalCrossEntropy
# CategoricalHinge
# CosineSimilarity
# FalseNegative
# FalsePositive
# Hinge
# KLDivergence
# LogCoshError
# Mean
# MeanAbolsuteError
# MeanAbsolutePercentageError
# MeanIou
# MeanRelatievError
# MeanSqaredError
# MeanSquaredLogarithmicError
# MeanTensor
# Poission
# PrecisionAtRecall
# Recall
# RecallAtPrecision
# RootMeanSquaredError
# SensitivityAtSpecificity
# SparseCatgoricalAccuracy
# SparseTopKCategoricalAccuracy
# SpecificityAtSensivity
# SquardHinge
# Sum
# TopKCategoricalAccuracy
# TrueNegative
# TruePositives

keras.metrics.BinaryCrossentropy