In [76]:
import math
import numpy as np

#sin_wave = np.array([math.sin(x) for x in np.arange(200)])
sin_wave = np.arange(0,50)

sin_wave

X = []
Y = []

seq_len = 4
num_records = len(sin_wave) - seq_len

In [77]:
sin_wave

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [78]:

for i in range(num_records - 2):
    X.append(sin_wave[i:i+seq_len])
    Y.append(sin_wave[i+seq_len])

In [79]:
X[:5]

[array([0, 1, 2, 3]),
 array([1, 2, 3, 4]),
 array([2, 3, 4, 5]),
 array([3, 4, 5, 6]),
 array([4, 5, 6, 7])]

In [ ]:
'''
We are considering first 4 records as input and Next immediate record as output 
You can see the same below

'''

In [83]:
Y[:6]

[4, 5, 6, 7, 8, 9]

In [84]:
len(X)

44

In [85]:
# Convert the input data in teh format of [batchsize,timestep,input feaures]

X = np.array(X)
X = np.expand_dims(X, axis=2)

In [89]:
X.shape  # batches = 44; timestep 4; input features = 1


(44, 4, 1)

In [90]:
X[0]   # first sample

array([[0],
       [1],
       [2],
       [3]])

In [91]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [92]:
# Define the RNN Archirecture for 

In [93]:
timestep = 4

hidden_dim = 8 # hidden unit
output_dim = 1

U = np.random.uniform(0, 1, (hidden_dim, timestep))  # weights between input and hidden layers
V = np.random.uniform(0, 1, (output_dim, hidden_dim)) # weights between hidden and output layers
W = np.random.uniform(0, 1, (hidden_dim, hidden_dim)) # shared weights in the RNN layer (hidden layer)

prev_s = np.zeros((hidden_dim, 1))

print("Time_step=2")
print("Hidden unit defined=",hidden_dim)

print("\nShape of the weights:")
print("U:{0} = Input to Hidden \nV:{1} = Previous to Hidden \nW:{2} = Hiden to Output".format(U.shape,V.shape,W.shape))
print("prev_s:{0} = previous output".format(prev_s.shape))

Time_step=2
Hidden unit defined= 8

Shape of the weights:
U:(8, 4) = Input to Hidden 
V:(1, 8) = Previous to Hidden 
W:(8, 8) = Hiden to Output
prev_s:(8, 1) = previous output


In [ ]:
'''
In the real scenario there will be 3 for loop will be implemented

1. Epoch
2. Number of samples
3. Timestep 


for epoch in range(epocs):
    for i in range(y.shape[0]):
        for t in range(timestep)
            ....
                RNN Implementation
            ....
            total loss for all time step
    ....
    Average the loss
    ....

'''

In [95]:
# lets Understnd how RNN calculating on the timestep for loop

print("Looking at my Input Shape")
print(X.shape)# Batches 0r samples = 44 and timestep = 4 and input feature =1

print("Time_step=2")
print("Hidden unit defined=",hidden_dim)

print("\n")

print("Weight shape from input to hidden unit (U):",U.shape)  # 5 becase my input sequence length is 5
print("Weight shape from Hidden to output (V):",V.shape)
print("Weight shape from previous output to hidden unit (W):",W.shape)


for t in range(timestep):
    print("***************************")
    print("Calculation for the {} Time step value".format(t))
    x = X[0] # conisder First sample or Batch Data
    
    new_input = np.zeros(x.shape)
    new_input[t] = x[t]
    
    print(new_input)
    print("Shape:",new_input.shape)
    
    print("Step 1: Dot product of the Input Sequence and U Weights")
    print("\tWeights from input to hidden shape:",U.shape)
    print("\tU:{0} and X_{1}:{2}".format(U.shape,t,new_input.shape))
    
    mulu = np.dot(U, new_input)
    
    print("\tShape of the output from tStep 1: ",mulu.shape)
    
    print("Step 2: Dot product of previous or shared weights and Hidden units")
    print("\tWights from previous or Shared to hidden shape:",V.shape)
    print("\tV:{0} and prev_s{1}:{2}".format(V.shape,t,prev_s.shape))
    
    mulw = np.dot(V, prev_s)
    
    print("\tShape of the output from Step 2: ",mulw.shape)
    
    print("Step 3: Add the output from Step1 and Step2")
    
    add = mulw + mulu    # add the both
    
    print("\tShape of the output from Step 3:{0}".format(add.shape))

    print("Step 4: Sigmoid Function of Step 3 output")
    
    s = sigmoid(add)   # (10,1)
    
    print("\tShape of the output from Step 4:{0}".format(s.shape))

    print("Step5: Dot product of output form step4 and  weights b/w hidden to output layers")
    mulv = np.dot(W, s) 
    #print(mulv)
    
    print("\nNote : Use the Output from the Step 4 (sigmoid) to Next timestep calculation")
    prev_s = s

Looking at my Input Shape
(44, 4, 1)
Time_step=2
Hidden unit defined= 8


Weight shape from input to hidden unit (U): (8, 4)
Weight shape from Hidden to output (V): (1, 8)
Weight shape from previous output to hidden unit (W): (8, 8)
***************************
Calculation for the 0 Time step value
[[0.]
 [0.]
 [0.]
 [0.]]
Shape: (4, 1)
Step 1: Dot product of the Input Sequence and U Weights
	Weights from input to hidden shape: (8, 4)
	U:(8, 4) and X_0:(4, 1)
	Shape of the output from tStep 1:  (8, 1)
Step 2: Dot product of previous or shared weights and Hidden units
	Wights from previous or Shared to hidden shape: (1, 8)
	V:(1, 8) and prev_s0:(8, 1)
	Shape of the output from Step 2:  (1, 1)
Step 3: Add the output from Step1 and Step2
	Shape of the output from Step 3:(8, 1)
Step 4: Sigmoid Function of Step 3 output
	Shape of the output from Step 4:(8, 1)
Step5: Dot product of output form step4 and  weights b/w hidden to output layers

Note : Use the Output from the Step 4 (sigmoid) to N