In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
'''

"thanks for an excellent report"

# Step1 : split the test
['thanks','for','an','excellent','report']

# Step 2: Interger Concoding
# word to Integer encoding
{
    'thanks' : 38,
    'for' : 39,
    'an' : 40,
    'excellent' : 19
    'report' :2
}

['thanks','for','an','excellent','report'] = [38, 39, 40, 19,  2]

# One Hot Encoding for the Same is 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)
        
# Shape : (5,41)

'''

In [225]:
One_hot_enc = to_categorical([38, 39, 40, 19,  2], num_classes=num_classes)

In [226]:
One_hot_enc.shape

(5, 41)

In [232]:
# first Time stamp 
# (10,41)(41,1)

timestep = 41
hidden_dim = 10
output_dim= 1
prev_s = np.zeros((hidden_dim, 1))

U = np.random.uniform(0,1,(hidden_dim,timestep))
V = np.random.uniform(0, 1, (output_dim, hidden_dim))

W = np.random.uniform(0,1,(hidden_dim,hidden_dim))

In [239]:
timestep = 5

for t in range(timestep):
    input = One_hot_enc[t].reshape(41,1)

    g1 = np.dot(U,input)
    g2 = np.dot(V,prev_s)
    
    add = g1 + g2 
    
    s = sigmoid(add)
    
    o = np.dot(W,s)
    
    prev_s = o
    
    print("Outpu for the Timestep:{0}".format(t))
    print(o)

Outpu for the Timestep:0
[[5.18524759]
 [5.86084101]
 [5.80918014]
 [5.73792418]
 [6.08850407]
 [6.23735258]
 [4.18456115]
 [3.88560102]
 [4.96861081]
 [4.93306849]]
Outpu for the Timestep:1
[[5.18524759]
 [5.86084101]
 [5.80918014]
 [5.73792418]
 [6.08850407]
 [6.23735258]
 [4.18456115]
 [3.88560102]
 [4.96861081]
 [4.93306849]]
Outpu for the Timestep:2
[[5.18524759]
 [5.86084101]
 [5.80918014]
 [5.73792418]
 [6.08850407]
 [6.23735258]
 [4.18456115]
 [3.88560102]
 [4.96861081]
 [4.93306849]]
Outpu for the Timestep:3
[[5.18524759]
 [5.86084101]
 [5.80918014]
 [5.73792418]
 [6.08850407]
 [6.23735258]
 [4.18456115]
 [3.88560102]
 [4.96861081]
 [4.93306849]]
Outpu for the Timestep:4
[[5.18524759]
 [5.86084101]
 [5.80918014]
 [5.73792418]
 [6.08850407]
 [6.23735258]
 [4.18456115]
 [3.88560102]
 [4.96861081]
 [4.93306849]]
