In [8]:
from keras.layers import Embedding

vocab_size = 44

embedding_layer = Embedding(input_dim = vocab_size,output_dim= 20, input_length=7)

# input_dims = size of the vocabulary in the text data

# output_dim = Each word in the vocabulary will be representaed as vector of dimenstion n : ex: 20 ;100; 200

# input_length = Length of the input sequence

In [ ]:
# Using Seq_converted text
model.add(Embedding(input_dim = vocab_size,output_dim= 20, input_length=7)) 


# Using pretrained model(embedding) 
model.add(Embedding(input_dim = vocab_size,output_dim = 100,weights = [embedding_matrix],input_length=7,trainable = False))

# Embedding_matrix: Emebedding matrix Generated from Pretrained Model


In [9]:
# Example : In below the example the corpus data having below the details

vocab_size = 44 #(it,good,you,should,...etc)

output_dim = 20 

input_length = 7 # ex: 'Wonderfully directed and executed I like it'

In [10]:
import numpy as np

In [11]:
import pandas as pd

# Corpus 
positive = ['This is an excellent movie','The move was fantastic I like it',
            'You should watch it is brilliant','Exceptionally good','Wonderfully directed and executed I like it',
             'Its a fantastic series','Never watched such a brillent movie','It is a Wonderful movie']

negative = ["horrible acting",'waste of money','pathetic picture','It was very boring',
            'I did not like the movie','The movie was horrible','I will not recommend',
            'The acting is pathetic']

reviews = [(pr,"positive") for pr in positive] + [(nr,"negative") for nr in negative]

data = pd.DataFrame(reviews,columns=["comment",'review'])

# shuffle the DataFrame rows
data = data.sample(frac = 1)

from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
data['review'] = lb_make.fit_transform(data["review"])

data.head(2)

comment  review
14    I will not recommend       0
13  The movie was horrible       0

In [12]:
# lower the text
data['comment'] = data['comment'].str.lower()

# find max_length sequence

max_seq_len = max([len([y for y in x.split()]) for x in data['comment']])
max_seq_len

7

In [13]:
# number of samples
num_samples = data.shape[0]
num_samples

16

In [14]:
from keras.preprocessing import text

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(data['comment'])
word2id = tokenizer.word_index

word2id['PAD'] = 0
id2word = {v:k for k, v in word2id.items()}
wids = [[word2id[w] for w in text.text_to_word_sequence(doc)] for doc in data['comment']]

In [15]:
vocabulary = [x for x,_ in word2id.items()]

vocabulary[:10]

['movie', 'it', 'i', 'the', 'is', 'was', 'like', 'a', 'not', 'horrible']

In [16]:
vocab_size = len(vocabulary)

vocab_size

44

In [17]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_inputs = pad_sequences(wids,padding='post')

padded_inputs

array([[ 3, 14,  9, 15,  0,  0,  0],
       [ 4,  1,  6, 10,  0,  0,  0],
       [16, 17, 18, 19,  3,  7,  2],
       [10, 11,  0,  0,  0,  0,  0],
       [ 2,  6, 20, 21,  0,  0,  0],
       [22, 23, 24,  0,  0,  0,  0],
       [ 3, 25,  9,  7,  4,  1,  0],
       [ 4, 11,  5, 12,  0,  0,  0],
       [26, 27, 28,  2,  5, 29,  0],
       [ 4, 30,  6, 13,  3,  7,  2],
       [31,  8, 13, 32,  0,  0,  0],
       [33, 34, 35,  8, 36,  1,  0],
       [12, 37,  0,  0,  0,  0,  0],
       [38, 39,  0,  0,  0,  0,  0],
       [ 2,  5,  8, 40,  1,  0,  0],
       [41,  5, 42, 43,  1,  0,  0]])

In [18]:

y = data['review'].values # output labels

y

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1])

In [19]:
from keras.models import Sequential
from keras.layers import Dense,Embedding,Flatten

model = Sequential()


# Input_dim = Vocabulary size of the corpus data
# output_dim = 
model.add(Embedding(input_dim = vocab_size,output_dim= 20, input_length=7))  # max_sequence_length = 7  vocab_size =44
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

print("Shape of the weights generated at layout0 ")
print(model.get_weights()[0].shape) # 44 : vocabulary(words) and Dimension :20

# Each word in the vocabulary will be representaed as vector of dimenstion 20


print("Shape of the weights generated at layout1 ")
print(model.get_weights()[1].shape)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Using Pretrained Embedding using 

print("Output of the Final Layer")
print(model.predict(padded_inputs).shape) # 16 samples) and output of each sample 

print(model.predict(padded_inputs))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Shape of the weights generated at layout0 
(44, 20)
Shape of the weights generated at layout1 
(140, 1)
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Output of the Final Layer

(16, 1)
[[0.50402147]
 [0.5070832 ]
 [0.4839696 ]
 [0.4902963 ]
 [0.510469  ]
 [0.50431097]
 [0.510008  ]
 [0.5104144 ]
 [0.50379044]
 [0.49965993]
 [0.51205456]
 [0.51506025]
 [0.49921316]
 [0.504286  ]
 [0.50896525]
 [0.49123123]]


In [20]:
from keras.models import Sequential
from keras.layers import Dense,Embedding,Flatten

model = Sequential()


# Input_dim = Vocabulary size of the corpus data
# output_dim = 
model.add(Embedding(input_dim = vocab_size,output_dim= 20, input_length=7))  # max_sequence_length = 7  vocab_size =44
#model.add(Flatten())
#model.add(Dense(1, activation='sigmoid'))


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Using Pretrained Embedding using 

print("Output of the Final Layer")
print(model.predict(padded_inputs).shape) #16 Samples, Max Sequence Length = 7 ,word Dimension =20 ;


Output of the Final Layer
(16, 7, 20)


In [21]:
from keras.models import Sequential
from keras.layers import Dense,Embedding,Flatten

model = Sequential()


# Input_dim = Vocabulary size of the corpus data
# output_dim = 
model.add(Embedding(input_dim = vocab_size,output_dim= 20, input_length=7))  # max_sequence_length = 7  vocab_size =44
model.add(Flatten())
#model.add(Dense(1, activation='sigmoid'))


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Using Pretrained Embedding using 

print("Output of the Final Layer")
print(model.predict(padded_inputs).shape) #16 and Length of 140 (Generated from previous layout output(20*7 =140))

Output of the Final Layer
(16, 140)


In [22]:
from keras.models import Sequential
from keras.layers import Dense,Embedding,Flatten

model = Sequential()


# Input_dim = Vocabulary size of the corpus data
# output_dim = 
model.add(Embedding(input_dim = vocab_size,output_dim= 20, input_length=7))  # max_sequence_length = 7  vocab_size =44
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Using Pretrained Embedding using 

print("Output of the Final Layer")
print(model.predict(padded_inputs).shape) #16 and Length of 140 (Generated from previous layout output(20*7 =140))

Output of the Final Layer
(16, 1)


In [23]:
# Word Emdedding using Alreday trained Model

In [24]:

from numpy import array
from numpy import asarray
from numpy import zeros

embeddings_dictionary = dict()

glove_file = open(r'C:\MyWork\MyLearning\Career Growth\ML\Files\DataSet\glove.6B.100d.txt', encoding="utf8")

for line in glove_file:
    records = line.split()
    word = records[0]
    vector_dimensions = asarray(records[1:], dtype='float32') 
    embeddings_dictionary[word] = vector_dimensions
glove_file.close()

In [40]:
vocab_size = len(vocabulary) + 1

vocab_size

45

In [26]:
import numpy as np

EMBEDDING_SIZE = 100
embedding_matrix = np.zeros((num_words, EMBEDDING_SIZE))

embedding_matrix.shape

(45, 100)

In [27]:
for word, index in word2id.items():
    embedding_vector = embeddings_dictionary.get(word)
    if embedding_vector is not None:
        embedding_matrix[index] = embedding_vector

In [41]:
from keras.models import Sequential
from keras.layers import Embedding

model = Sequential()

# num_words = vocabulary size
# input_length : 7 : Max_seq_length

model.add(Embedding(input_dim = vocab_size,output_dim = 100,weights = [embedding_matrix],input_length=7,trainable = False))

model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [33]:
model.get_weights()[0].shape  # output from the first layer of 45,100 ; 45 words and each of dimension 100

(45, 100)

In [49]:
model.predict(np.array([ 4,  1,  6, 10,  0,  0,  0]).reshape(1,7))

array([[0.6169161]], dtype=float32)