In [ ]:
'''

Core Layers
    - Dense
    - Flattern
    - Dropout
    - Reshape
    - Permute
    - RepeatVector
    - Lambda
    - Pooling
    - Locally Connected Layer

'''

In [ ]:
'''
Dense : ***Check in the Main Node of Latey


'''

In [ ]:
'''
Flattern :  Return the array collapsed into one dimension.

    - Flatten is used to flatten the input.
    - If Input shape as (batch_size, 2,2),then the output shape of the layer will be (batch_size, 4)

'''

In [2]:
import numpy as np
import random

data = np.arange(0,24).reshape(1,3,2,4)

print(data)

print("\n")

print("AFtre Flattern data")
data.flatten()

[[[[ 0  1  2  3]
   [ 4  5  6  7]]

  [[ 8  9 10 11]
   [12 13 14 15]]

  [[16 17 18 19]
   [20 21 22 23]]]]


AFtre Flattern data


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense,Flatten

model = Sequential() 
layer_1 = Dense(8,input_shape = (6,6))
model.add(layer_1)

layer_2 = Flatten() 
model.add(layer_2)


print("Input shape at Dese Layer:",layer_1.input_shape)
print("Output shape at Dese Layer:",layer_1.output_shape)

print("\n")

print("Input shape at Flatten Layer:",layer_2.input_shape)
print("Output shape at Flatten Layer:",layer_2.output_shape)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Input shape at Dese Layer: (None, 6, 6)
Output shape at Dese Layer: (None, 6, 8)


Input shape at Flatten Layer: (None, 6, 8)
Output shape at Flatten Layer: (None, 48)


In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6, 8)              56        
_________________________________________________________________
flatten (Flatten)            (None, 48)                0         
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________


In [5]:
import numpy as np
from tensorflow.keras.layers import Input,Flatten
from tensorflow.keras.models import Model

inputs = Input(shape=(3,2,4))

prediction = Flatten()(inputs)

model = Model(inputs=inputs, outputs=prediction)
X = np.arange(0,24).reshape(1,3,2,4)

print(model.predict(X))

model.summary()

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23.]]
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3, 2, 4)]         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 24)                0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [6]:
# Define the Input
inputs = Input(shape=(4,3))

# Define output : Flatten 
output  = Flatten()(inputs)

# Defn Model
model = Model(inputs=inputs, outputs=output)

# Predict the : convert 3 D Array to 1 D

X = np.arange(0,12).reshape(1,4,3)
print(X)


model.predict(X)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)

In [8]:
model.predict(X).shape

(1, 12)

In [9]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 1, 4, 3)]         0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 12)                0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [ ]:
'''
Dropout : ***Check in the Main Node of Latey

'''

In [ ]:
'''
Reshape:
    - Layer that reshapes inputs into the given shape.

'''

In [11]:
from tensorflow.keras.layers import Reshape

model = Sequential() 
 
model.add(Dense(16, input_shape = (4,3)))
model.add(Reshape((8,8)))

print(model.layers[0].input)
print(model.layers[0].output)

print("\n")
print("After Reshape:")

print(model.layers[1].input)
print(model.layers[1].output)


Tensor("dense_2_input:0", shape=(?, 4, 3), dtype=float32)
Tensor("dense_2/BiasAdd:0", shape=(?, 4, 16), dtype=float32)


After Reshape:
Tensor("dense_2/BiasAdd:0", shape=(?, 4, 16), dtype=float32)
Tensor("reshape/Reshape:0", shape=(?, 8, 8), dtype=float32)


In [12]:
model = Sequential()
model.add(Reshape((-1, 2, 2),input_shape=(12,)))


#print("Layer that reshapes inputs into the given shape.")
print(model.layers[0].input)
print(model.layers[0].output)

Tensor("reshape_1_input:0", shape=(?, 12), dtype=float32)
Tensor("reshape_1/Reshape:0", shape=(?, ?, 2, 2), dtype=float32)


In [ ]:
'''
Permute :

 - Output shape: Same as the input shape, but with the dimensions re-ordered according to the specified pattern.
 - For instance, `(2, 1)` permutes the first and second dimensionsof the input

'''

In [13]:
from tensorflow.keras.layers import Permute

model = Sequential() 
model.add(Dense(16, input_shape = (4, 3)))
model.add(Permute((2, 1)) )

print(model.layers[0].input_shape)
print(model.layers[0].output_shape)

print("\n")
print(model.layers[1].input_shape)
print(model.layers[1].output_shape)

(None, 4, 3)
(None, 4, 16)


(None, 4, 16)
(None, 16, 4)


In [ ]:
'''
RepeatVector:
    - It is used to repeat the input for set number, n of times
    - RepeatVector(16) Ex : Input : (batch_size, 32)  Output: (batch_size, 16, 32)

'''

In [14]:
from tensorflow.keras.layers import RepeatVector

model = Sequential() 
model.add(Dense(16, input_shape=(8,)))
model.add(RepeatVector(3))


print(model.layers[0].input_shape)
print(model.layers[0].output_shape)

print("\n")
print(model.layers[1].input_shape)
print(model.layers[1].output_shape)

'''
Note :

Input shape:2D tensor
Output shape:3D tensor

'''

(None, 8)
(None, 16)


(None, 16)
(None, 3, 16)


'\nNote :\n\nInput shape:2D tensor\nOutput shape:3D tensor\n\n'

In [ ]:
'''
Lambda:
    - Lambda is used to transform the input data using an expression or function
'''

In [ ]:
'''
Pooling:

'''

In [ ]:
'''
Locally Connected Layer

'''