In [1]:
import tensorflow as tf
tf.enable_eager_execution

<function tensorflow.python.framework.ops.enable_eager_execution(config=None, device_policy=None, execution_mode=None)>

In [21]:
from tensorflow.keras.layers import Input,Dense
from tensorflow.keras.models import Model\

import numpy as np

In [31]:
# this is a logistic regression in Keras

x = Input(shape=(32,))
y = Dense(16, activation='softmax')(x)
model = Model(x, y)

input = np.arange(1,33).reshape(1,32)

print("input:",input)

print("\n")
print("Predicted:",model.predict(input))


# sum of all the values predicted is equal to 1
print(model.predict(input).sum())

input: [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32]]


Predicted: [[2.5880979e-22 1.1170376e-27 5.9400707e-02 7.4618703e-01 1.9382611e-01
  1.8765720e-23 6.0524497e-31 5.8613281e-04 1.8906602e-33 2.2522326e-17
  3.1827080e-16 4.3693632e-20 6.4720188e-11 3.2668765e-20 3.5623360e-20
  7.2109825e-20]]
1.0


In [35]:

#02 Example

x = Input(shape=(32,))
y = tf.square(x)  # This op will be treated like a layer
model = Model(x, y)

input = np.arange(1,33).reshape(1,32)

print("Predicted:",model.predict(input))

Predicted: [[1.000e+00 4.000e+00 9.000e+00 1.600e+01 2.500e+01 3.600e+01 4.900e+01
  6.400e+01 8.100e+01 1.000e+02 1.210e+02 1.440e+02 1.690e+02 1.960e+02
  2.250e+02 2.560e+02 2.890e+02 3.240e+02 3.610e+02 4.000e+02 4.410e+02
  4.840e+02 5.290e+02 5.760e+02 6.250e+02 6.760e+02 7.290e+02 7.840e+02
  8.410e+02 9.000e+02 9.610e+02 1.024e+03]]


In [37]:
# 03 Exmaple

inputa = Input(shape=(32,))

x = Dense(8, activation="relu")(inputa)

model = Model(inputs=inputa, outputs=x)

input = np.arange(1,33).reshape(1,32)

model.predict(input)

array([[46.18094 ,  0.      , 26.811028,  0.      , 13.276486,  0.      ,
        30.110012, 19.236961]], dtype=float32)

In [42]:
# 04 Like Functional API


inputs = Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)

outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

model.predict(np.arange(1,4).reshape(1,3))

array([[0.05485607, 0.05375284, 0.08596317, 0.79567105, 0.00975693]],
      dtype=float32)

In [56]:
# 05 

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input,Dense

model = Sequential()
model.add(Input(shape=(4,)))
model.add(Dense(2, activation="relu"))

model.summary()

x =  np.arange(1,5).reshape(1,4)
model.predict(x)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


array([[3.552338  , 0.92512655]], dtype=float32)

In [58]:
# above the exmaple can be modifed futher Define Input on the Dense Layer with 'input_shape'

model = Sequential()
model.add(Dense(2, activation="relu", input_shape=(4,)))

model.summary()

x =  np.arange(1,5).reshape(1,4)
model.predict(x)

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_19 (Dense)             (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


array([[0.59710836, 0.        ]], dtype=float32)

In [60]:
# above the exmaple can be modifed futher Define Input on the Dense Layer with 'input_dim'

model = Sequential()
model.add(Dense(2, activation="relu", input_dim=4))

model.summary()

x =  np.arange(1,5).reshape(1,4)
model.predict(x)

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_21 (Dense)             (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


array([[0.       , 1.5173178]], dtype=float32)

In [61]:
# Multilayer Perceptron

from tensorflow.keras.utils import plot_model
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
visible = Input(shape=(10,))                        # Define Input
hidden1 = Dense(10, activation='relu')(visible)
hidden2 = Dense(20, activation='relu')(hidden1)
hidden3 = Dense(10, activation='relu')(hidden2)
output = Dense(1, activation='sigmoid')(hidden3)
model = Model(inputs=visible, outputs=output)
# summarize layers
print(model.summary())

Model: "model_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_25 (InputLayer)        [(None, 10)]              0         
_________________________________________________________________
dense_22 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_23 (Dense)             (None, 20)                220       
_________________________________________________________________
dense_24 (Dense)             (None, 10)                210       
_________________________________________________________________
dense_25 (Dense)             (None, 1)                 11        
Total params: 551
Trainable params: 551
Non-trainable params: 0
_________________________________________________________________
None


In [64]:
# Convolutional Neural Network

# Convolutional Neural Network
from tensorflow.keras.utils import plot_model
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D

visible = Input(shape=(64,64,1))                                    # Define Input

conv1 = Conv2D(32, kernel_size=4, activation='relu')(visible)
pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)
conv2 = Conv2D(16, kernel_size=4, activation='relu')(pool1)
pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)
flat = Flatten()(pool2)
hidden1 = Dense(10, activation='relu')(flat)
output = Dense(1, activation='sigmoid')(hidden1)
model = Model(inputs=visible, outputs=output)
# summarize layers
print(model.summary())

Model: "model_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_26 (InputLayer)        [(None, 64, 64, 1)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 61, 61, 32)        544       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 30, 30, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 27, 27, 16)        8208      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 16)        0         
_________________________________________________________________
flatten (Flatten)            (None, 2704)              0         
_________________________________________________________________
dense_26 (Dense)             (None, 10)                270

In [66]:
# RNN


# Recurrent Neural Network
from tensorflow.keras.utils import plot_model
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
 
visible = Input(shape=(100,1))                          # Define Input
hidden1 = LSTM(10)(visible)
hidden2 = Dense(10, activation='relu')(hidden1)

output = Dense(1, activation='sigmoid')(hidden2)
model = Model(inputs=visible, outputs=output)
# summarize layers
print(model.summary())

Model: "model_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_27 (InputLayer)        [(None, 100, 1)]          0         
_________________________________________________________________
lstm (LSTM)                  (None, 10)                480       
_________________________________________________________________
dense_28 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_29 (Dense)             (None, 1)                 11        
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________
None
