In [ ]:
# Activate Function uage with Dense Layer also calculate the same Manualy

In [ ]:
import tensorflow as tf
tf.enable_eager_execution

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation
from tensorflow.keras import activations

In [25]:
# Sigmoid

model = Sequential()
model.add(Dense(2, input_dim =2))
model.add(Activation(activations.sigmoid))

import numpy as np
input = np.arange(2,10).reshape(4,2)

print("define input:")
print(input)

print("\n")
print("Final predict after sigmoid")
model.predict(x)

define input:
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


Final predict after sigmoid


array([[0.41714224, 0.2281313 ],
       [0.28577688, 0.20785451],
       [0.18280584, 0.18893877],
       [0.11116257, 0.17137203]], dtype=float32)

In [33]:
# lets do the same Manully

# lets get the  weights
w = model.layers[0].get_weights()[0]
b = model.layers[0].get_weights()[1]

# manully Compute the Z function
z = np.dot(x,w) + b

# Activation Function mnually calculate
1 / (1 + np.exp(-z))

array([[0.41714224, 0.22813129],
       [0.28577688, 0.20785447],
       [0.18280584, 0.18893874],
       [0.11116261, 0.17137202]])

In [79]:
# Relu

model = Sequential()
model.add(Dense(2, input_dim =2))
model.add(Activation(activations.relu))

import numpy as np
input = np.arange(2,10).reshape(4,2)

print("define input:")
print(input)

print("\n")
print("Final predict after Relu")
model.predict(x)

define input:
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


Final predict after Relu


array([[ 5.191078,  0.      ],
       [ 9.249054,  0.      ],
       [13.30703 ,  0.      ],
       [17.365005,  0.      ]], dtype=float32)

In [80]:
# lets do the same Manully

# lets get the  weights
w = model.layers[0].get_weights()[0]
b = model.layers[0].get_weights()[1]

# manully Compute the Z function
z = np.dot(x,w) + b

# Activation Function mnually calculate
np.maximum(0,z)

array([[ 5.19107807,  0.        ],
       [ 9.24905431,  0.        ],
       [13.30703056,  0.        ],
       [17.3650068 ,  0.        ]])

In [83]:
# Relu 

from tensorflow.keras.activations import relu

model = Sequential()
model.add(Dense(1, input_dim =1))
model.add(Activation(activations.relu))

foo = np.array([-10, -5, 0.0, 5, 10,15]).reshape(6,1)

model.predict(foo)

array([[0.       ],
       [0.       ],
       [0.       ],
       [3.1479888],
       [6.2959776],
       [9.443967 ]], dtype=float32)

In [85]:
# Relu  : manualy

# lets do the same Manully

# lets get the  weights
w = model.layers[0].get_weights()[0]
b = model.layers[0].get_weights()[1]

# manully Compute the Z function
z = np.dot(foo,w) + b

# Activation Function mnually calculate
np.maximum(0,z)


array([[0.        ],
       [0.        ],
       [0.        ],
       [3.14798892],
       [6.29597783],
       [9.44396675]])

In [91]:
# Rellu with Alpha value = 5

model = Sequential()
model.add(Dense(1, input_dim =1))
model.add(Activation(activation=tf.keras.layers.ReLU(max_value=5)))

foo = np.array([-10, -5, 0.0, 5, 10,15]).reshape(6,1)

model.predict(foo)

array([[0.],
       [0.],
       [0.],
       [5.],
       [5.],
       [5.]], dtype=float32)

In [109]:
# Relu  : manualy

# lets do the same Manully

alpha = 5

# lets get the  weights
w = model.layers[0].get_weights()[0]
b = model.layers[0].get_weights()[1]

# manully Compute the Z function
z = np.dot(foo,w) + b

# Activation Function mnually calculate
out = np.maximum(0,z)

np.array([alpha if i>alpha else i[0] for i in out])

array([0., 0., 0., 5., 5., 5.])

In [335]:
# Softmax:

from tensorflow.keras.layers import Input

model = Sequential()
#model.add(Input(shape=1))
model.add(Dense(2,input_dim =1, activation='softmax'))

x = np.asarray([1., 2., 1.])

model.predict(x)

array([[0.6766114 , 0.3233886 ],
       [0.814041  , 0.18595897],
       [0.6766114 , 0.3233886 ]], dtype=float32)

In [336]:
# manully Calcuate : output from the above the mdoel is not same as manully 
# caluated need to check the same
w = model.layers[0].get_weights()[0]

z = np.dot(inp,w)

np.exp(z) / np.exp(z).sum()

array([[0.13002312, 0.06214497],
       [0.50117561, 0.1144882 ],
       [0.13002312, 0.06214497]])

In [341]:
# softplus

model = Sequential()
model.add(Dense(2, input_dim =2))
model.add(Activation(activations.softplus))

import numpy as np
input = np.arange(2,10).reshape(4,2)

print("define input:")
print(input)

print("\n")
print("Final predict after softplus")
model.predict(input)

define input:
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


Final predict after Relu


array([[0.72955996, 2.1329372 ],
       [0.4466554 , 3.0450504 ],
       [0.2586362 , 4.004161  ],
       [0.14386064, 4.9821024 ]], dtype=float32)

In [348]:
# manully Calculating the same

w = model.layers[0].get_weights()[0]

z = np.dot(input,w)

np.log(np.exp(z) + 1)

array([[0.72956006, 2.13293745],
       [0.44665536, 3.04505029],
       [0.25863613, 4.00416104],
       [0.14386071, 4.98210287]])

In [351]:
# softsign

model = Sequential()
model.add(Dense(2, input_dim =2))
model.add(Activation(activations.softsign))

import numpy as np
input = np.arange(2,10).reshape(4,2)

print("define input:")
print(input)

print("\n")
print("Final predict after softsign")
model.predict(input)

define input:
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


Final predict after softplus


array([[ 0.7819857 , -0.737293  ],
       [ 0.8703581 , -0.82441723],
       [ 0.90775126, -0.86814547],
       [ 0.9284024 , -0.8944359 ]], dtype=float32)

In [352]:
# manully Calculating the same

w = model.layers[0].get_weights()[0]

z = np.dot(input,w)

z / (abs(z) + 1)

array([[ 0.78198572, -0.73729302],
       [ 0.87035812, -0.82441722],
       [ 0.90775128, -0.86814548],
       [ 0.92840246, -0.89443586]])

In [353]:
# tangent 

model = Sequential()
model.add(Dense(2, input_dim =2))
model.add(Activation(activations.tanh))

import numpy as np
input = np.arange(2,10).reshape(4,2)

print("define input:")
print(input)

print("\n")
print("Final predict after softsign")
model.predict(input)

define input:
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


Final predict after softsign


array([[-0.997195  ,  0.97446793],
       [-0.99998575,  0.9983314 ],
       [-1.        ,  0.9998922 ],
       [-1.        ,  0.9999931 ]], dtype=float32)

In [360]:
# manully Calculating the same

w = model.layers[0].get_weights()[0]

z = np.dot(input,w)

#01
((np.exp(z) - np.exp(-z))/(np.exp(z) + np.exp(-z)))

array([[-0.99719499,  0.97446796],
       [-0.99998581,  0.99833143],
       [-0.99999993,  0.99989217],
       [-1.        ,  0.99999304]])

In [364]:
#02

np.sinh(z)/np.cosh(z) 

array([[-0.99719499,  0.97446796],
       [-0.99998581,  0.99833143],
       [-0.99999993,  0.99989217],
       [-1.        ,  0.99999304]])

In [373]:
#03

def sigmoid(x):
    return 1 / (1 + np.exp(-z))

(2 * sigmoid(2*z)) - 1

array([[-0.92775486,  0.79579157],
       [-0.99468626,  0.94383099],
       [-0.99962135,  0.98542154],
       [-0.99997308,  0.99627523]])

In [375]:
# exponential 

model = Sequential()
model.add(Dense(2, input_dim =2))
model.add(Activation(activations.exponential))

import numpy as np
input = np.arange(2,10).reshape(4,2)

print("define input:")
print(input)

print("\n")
print("Final predict after softsign")
model.predict(input)

define input:
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


Final predict after softsign


array([[7.8117728e-01, 4.9832337e-02],
       [1.0037411e+00, 5.4222047e-03],
       [1.2897147e+00, 5.8998505e-04],
       [1.6571651e+00, 6.4195658e-05]], dtype=float32)

In [376]:
# manully Calculating the same

w = model.layers[0].get_weights()[0]

z = np.dot(input,w)

#01
np.exp(z)

array([[7.81177307e-01, 4.98323350e-02],
       [1.00374097e+00, 5.42220655e-03],
       [1.28971481e+00, 5.89984874e-04],
       [1.65716488e+00, 6.41956643e-05]])

In [380]:
# elu 

model = Sequential()
model.add(Dense(2, input_dim =2))
model.add(Activation(activations.elu)) # default alpha = 1.0

import numpy as np
input = np.arange(2,10).reshape(4,2)

print("define input:")
print(input)

print("\n")
print("Final predict after softsign")
model.predict(input)

define input:
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


Final predict after softsign


array([[-0.92519593, -0.9074605 ],
       [-0.98939127, -0.97091126],
       [-0.99849546, -0.9908563 ],
       [-0.9997866 , -0.9971258 ]], dtype=float32)

In [439]:
# manully Calculating the same

w = model.layers[0].get_weights()[0]

z = np.dot(input,w)

# f(x) = x for x >= 0
# f(x) =  alpha * (exp(x) - 1.) for x < 0

values = []

for i in range(len(z)):
    values.append([x if x>=0 else (alpha * (np.exp(x) - 1)) for x in z[i]])
    
values

[[-0.9251958993218959, -0.9074605094372521],
 [-0.9893912661463615, -0.9709112582284117],
 [-0.99849546705385, -0.9908562831639925],
 [-0.9997866268098267, -0.9971257760740017]]

In [442]:
# selu 

model = Sequential()
model.add(Dense(2, input_dim =2))
model.add(Activation(activations.selu())) # default alpha = 1.67326324 and scale = 1.05070098

import numpy as np
input = np.arange(2,10).reshape(4,2)

print("define input:")
print(input)

print("\n")
print("Final predict after softsign")
model.predict(input)

define input:
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


Final predict after softsign


array([[-1.5612097,  1.343575 ],
       [-1.7299442,  2.1472173],
       [-1.7540733,  2.9508598],
       [-1.7575237,  3.7545018]], dtype=float32)

In [447]:
# manully Calculating the same

w = model.layers[0].get_weights()[0]

z = np.dot(input,w)

# if x > 0: return scale * x
# if x < 0: return scale * alpha * (exp(x) - 1)
# constants (alpha=1.67326324 and scale=1.05070098)

alpha = 1.67326324
scale = 1.05070098

values = []

for i in range(len(z)):
    values.append([(scale*x) if x>=0 else (scale * alpha * (np.exp(x) - 1)) for x in z[i]])
    
values

[[-1.561209657395137, 1.3435749250678755],
 [-1.7299442644599141, 2.147217243675835],
 [-1.75407317528116, 2.950859562283795],
 [-1.7575235897962815, 3.7545018808917545]]