In [1]:
import numpy as np
import tensorflow as tf

In [22]:
# input data
X_data = np.array([
# steps   1st     2nd       3rd
        [[1, 2], [7, 8], [13, 14]],  # first batch
        [[3, 4], [9, 10], [15, 16]], # second batch
        [[5, 6], [11, 12], [17, 18]] # third batch
]) # shape: [batch_size, n_steps, n_inputs]

X_data

array([[[ 1,  2],
        [ 7,  8],
        [13, 14]],

       [[ 3,  4],
        [ 9, 10],
        [15, 16]],

       [[ 5,  6],
        [11, 12],
        [17, 18]]])

In [17]:
X_data.shape  # Sample Or Batch =3;Time step = 3;Input =2

(3, 3, 2)

In [18]:
X_data[0,:,:] # First batch values

array([[ 1,  2],
       [ 7,  8],
       [13, 14]])

In [19]:
X_data[1,:,:] # Second batch values

array([[ 3,  4],
       [ 9, 10],
       [15, 16]])

In [20]:
X_data[2,:,:] # Third batch values

array([[ 5,  6],
       [11, 12],
       [17, 18]])

In [21]:
# Consider Fist Input from all the time-step and batches
X_data[:,:,0]

array([[ 1,  7, 13],
       [ 3,  9, 15],
       [ 5, 11, 17]])