In [2]:
import numpy as np
import tensorflow as tf

In [3]:
np.random.seed(1)

# Example 1:
x = np.random.randn(3,10,4) # Sample or Batch=3;Time Step =10;Input or Feature = 4

In [4]:
x

array([[[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
        [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ],
        [ 0.3190391 , -0.24937038,  1.46210794, -2.06014071],
        [-0.3224172 , -0.38405435,  1.13376944, -1.09989127],
        [-0.17242821, -0.87785842,  0.04221375,  0.58281521],
        [-1.10061918,  1.14472371,  0.90159072,  0.50249434],
        [ 0.90085595, -0.68372786, -0.12289023, -0.93576943],
        [-0.26788808,  0.53035547, -0.69166075, -0.39675353],
        [-0.6871727 , -0.84520564, -0.67124613, -0.0126646 ],
        [-1.11731035,  0.2344157 ,  1.65980218,  0.74204416]],

       [[-0.19183555, -0.88762896, -0.74715829,  1.6924546 ],
        [ 0.05080775, -0.63699565,  0.19091548,  2.10025514],
        [ 0.12015895,  0.61720311,  0.30017032, -0.35224985],
        [-1.1425182 , -0.34934272, -0.20889423,  0.58662319],
        [ 0.83898341,  0.93110208,  0.28558733,  0.88514116],
        [-0.75439794,  1.25286816,  0.51292982, -0.29809284],
      

In [5]:
# First Feature 
x[:,:,0] # here we are considring first input or featue from all sample in all batches

array([[ 1.62434536,  0.86540763,  0.3190391 , -0.3224172 , -0.17242821,
        -1.10061918,  0.90085595, -0.26788808, -0.6871727 , -1.11731035],
       [-0.19183555,  0.05080775,  0.12015895, -1.1425182 ,  0.83898341,
        -0.75439794,  0.48851815,  2.18557541,  0.16003707, -0.30620401],
       [-0.22232814,  0.19829972,  0.12182127, -0.37528495, -0.34385368,
        -0.44712856, -1.09491185, -0.26621851,  0.84616065, -0.03869551]])

In [6]:
# Second Feature
x[:,:,1] # here we are considring second input or featue from all sample in all batches

array([[-0.61175641, -2.3015387 , -0.24937038, -0.38405435, -0.87785842,
         1.14472371, -0.68372786,  0.53035547, -0.84520564,  0.2344157 ],
       [-0.88762896, -0.63699565,  0.61720311, -0.34934272,  0.93110208,
         1.25286816, -0.07557171, -1.39649634,  0.87616892,  0.82797464],
       [-0.20075807,  0.11900865,  1.12948391, -0.63873041,  0.04359686,
         1.2245077 ,  0.16938243,  0.03261455, -0.85951594, -1.61577235]])

In [7]:
# Third Feature
x[:,:,2]

array([[-0.52817175,  1.74481176,  1.46210794,  1.13376944,  0.04221375,
         0.90159072, -0.12289023, -0.69166075, -0.67124613,  1.65980218],
       [-0.74715829,  0.19091548,  0.30017032, -0.20889423,  0.28558733,
         0.51292982,  1.13162939, -1.44411381,  0.31563495,  0.23009474],
       [ 0.18656139, -0.67066229,  1.19891788,  0.42349435, -0.62000084,
         0.40349164,  0.74055645, -1.37311732,  0.35054598,  1.12141771]])

In [8]:
# Fourth Feature
x[:,:,3] # here we are considring Third input or featue from all sample in all batches

array([[-1.07296862, -0.7612069 , -2.06014071, -1.09989127,  0.58281521,
         0.50249434, -0.93576943, -0.39675353, -0.0126646 ,  0.74204416],
       [ 1.6924546 ,  2.10025514, -0.35224985,  0.58662319,  0.88514116,
        -0.29809284,  1.51981682, -0.50446586, -2.02220122,  0.76201118],
       [ 0.41005165,  0.37756379,  0.18515642,  0.07734007,  0.69803203,
         0.59357852, -0.9537006 ,  0.31515939, -1.31228341,  0.40890054]])

In [11]:
# First batch values

x[0,:,:]

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038,  1.46210794, -2.06014071],
       [-0.3224172 , -0.38405435,  1.13376944, -1.09989127],
       [-0.17242821, -0.87785842,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434],
       [ 0.90085595, -0.68372786, -0.12289023, -0.93576943],
       [-0.26788808,  0.53035547, -0.69166075, -0.39675353],
       [-0.6871727 , -0.84520564, -0.67124613, -0.0126646 ],
       [-1.11731035,  0.2344157 ,  1.65980218,  0.74204416]])

In [12]:
# Second batch values

x[1,:,:]

array([[-0.19183555, -0.88762896, -0.74715829,  1.6924546 ],
       [ 0.05080775, -0.63699565,  0.19091548,  2.10025514],
       [ 0.12015895,  0.61720311,  0.30017032, -0.35224985],
       [-1.1425182 , -0.34934272, -0.20889423,  0.58662319],
       [ 0.83898341,  0.93110208,  0.28558733,  0.88514116],
       [-0.75439794,  1.25286816,  0.51292982, -0.29809284],
       [ 0.48851815, -0.07557171,  1.13162939,  1.51981682],
       [ 2.18557541, -1.39649634, -1.44411381, -0.50446586],
       [ 0.16003707,  0.87616892,  0.31563495, -2.02220122],
       [-0.30620401,  0.82797464,  0.23009474,  0.76201118]])

In [14]:
# Third batch values

x[2,:,:]

array([[-0.22232814, -0.20075807,  0.18656139,  0.41005165],
       [ 0.19829972,  0.11900865, -0.67066229,  0.37756379],
       [ 0.12182127,  1.12948391,  1.19891788,  0.18515642],
       [-0.37528495, -0.63873041,  0.42349435,  0.07734007],
       [-0.34385368,  0.04359686, -0.62000084,  0.69803203],
       [-0.44712856,  1.2245077 ,  0.40349164,  0.59357852],
       [-1.09491185,  0.16938243,  0.74055645, -0.9537006 ],
       [-0.26621851,  0.03261455, -1.37311732,  0.31515939],
       [ 0.84616065, -0.85951594,  0.35054598, -1.31228341],
       [-0.03869551, -1.61577235,  1.12141771,  0.40890054]])