In [1]:
import numpy as np
import tensorflow as tf

In [3]:
X = list()
y = list()

X = [x+1 for x in range(20)]
Y = [y*15 for y in X]

print("X={0}".format(X))
print("Y={0}".format(Y))

X=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Y=[15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300]


In [11]:
# Reshape the Input Data in 3D 

X = np.array(X).reshape(20,1,1)
#print(X)   # 20 Sample timestep =1 and single Feature

X

array([[[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]]])

In [30]:
# Example 2

X = np.array([30])

X = X.reshape((1, 1, 1))

print(X)  # Sample =1 and Time step = 1 and Feature = 1

[[[30]]]


In [40]:
# Example 3

X1 = [(x+1)*2 for x in range(25)]
X2 = [(x+1)*3 for x in range(25)]
Y = [x1*x2 for x1,x2 in zip(X1,X2)]

print("X1={0}".format(X1))
print("X2={0}".format(X2))
print("Y={0}".format(Y))

print("\n")

X = np.column_stack((X1, X2))
print(X)
X = np.array(X).reshape(25,1,2)

print("\n\n")
print("After Reshape")
print(X) # Sample = 25 and time step =1 and Feature = 2

X1=[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
X2=[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75]
Y=[6, 24, 54, 96, 150, 216, 294, 384, 486, 600, 726, 864, 1014, 1176, 1350, 1536, 1734, 1944, 2166, 2400, 2646, 2904, 3174, 3456, 3750]


[[ 2  3]
 [ 4  6]
 [ 6  9]
 [ 8 12]
 [10 15]
 [12 18]
 [14 21]
 [16 24]
 [18 27]
 [20 30]
 [22 33]
 [24 36]
 [26 39]
 [28 42]
 [30 45]
 [32 48]
 [34 51]
 [36 54]
 [38 57]
 [40 60]
 [42 63]
 [44 66]
 [46 69]
 [48 72]
 [50 75]]



After Reshape
[[[ 2  3]]

 [[ 4  6]]

 [[ 6  9]]

 [[ 8 12]]

 [[10 15]]

 [[12 18]]

 [[14 21]]

 [[16 24]]

 [[18 27]]

 [[20 30]]

 [[22 33]]

 [[24 36]]

 [[26 39]]

 [[28 42]]

 [[30 45]]

 [[32 48]]

 [[34 51]]

 [[36 54]]

 [[38 57]]

 [[40 60]]

 [[42 63]]

 [[44 66]]

 [[46 69]]

 [[48 72]]

 [[50 75]]]


In [44]:
# Many to One Sequence

X = np.array([x+1 for x in range(45)])
print(X)

X = X.reshape(15,3,1)

print("\n")

print(X) # Sample = 15 and Time step =3 and Feature = 1

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]


[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]

 [[19]
  [20]
  [21]]

 [[22]
  [23]
  [24]]

 [[25]
  [26]
  [27]]

 [[28]
  [29]
  [30]]

 [[31]
  [32]
  [33]]

 [[34]
  [35]
  [36]]

 [[37]
  [38]
  [39]]

 [[40]
  [41]
  [42]]

 [[43]
  [44]
  [45]]]


In [57]:
# Many to One Sequence Problem with Multiple Features

X1 = np.array([x+3 for x in range(0, 135, 3)])
print("X1={0}".format(X1))

X2 = np.array([x+5 for x in range(0, 225, 5)])
print("X2={0}".format(X2))

print("\n")
X = np.column_stack((X1, X2))
print("X=\n{0}".format(X))

X = np.array(X).reshape(15,3,2)  

print("\n")

print(X) # Sample = 15 and Time step =3 and Features =2

X1=[  3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51  54
  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108
 111 114 117 120 123 126 129 132 135]
X2=[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200 205 210 215 220 225]


X=
[[  3   5]
 [  6  10]
 [  9  15]
 [ 12  20]
 [ 15  25]
 [ 18  30]
 [ 21  35]
 [ 24  40]
 [ 27  45]
 [ 30  50]
 [ 33  55]
 [ 36  60]
 [ 39  65]
 [ 42  70]
 [ 45  75]
 [ 48  80]
 [ 51  85]
 [ 54  90]
 [ 57  95]
 [ 60 100]
 [ 63 105]
 [ 66 110]
 [ 69 115]
 [ 72 120]
 [ 75 125]
 [ 78 130]
 [ 81 135]
 [ 84 140]
 [ 87 145]
 [ 90 150]
 [ 93 155]
 [ 96 160]
 [ 99 165]
 [102 170]
 [105 175]
 [108 180]
 [111 185]
 [114 190]
 [117 195]
 [120 200]
 [123 205]
 [126 210]
 [129 215]
 [132 220]
 [135 225]]


[[[  3   5]
  [  6  10]
  [  9  15]]

 [[ 12  20]
  [ 15  25]
  [ 18  30]]

 [[ 21  35]
  [ 24  40]
  [ 27  45]]

 [[ 30  5

In [6]:
import numpy as np

X = [x for x in range(10)]

X = np.array(X).reshape(10,1,1) # One to One Sequence # 

X

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])