In [ ]:
'''
Weights Initializer
    1. kernel_initializer
    2. bias_initializer 

'''

In [ ]:
'''
Layer Weight Initilizer
    1. RandomNormal class
    2. RandomUniform class
    3. TruncatedNormal class
    4. Zeros class
    5. Ones class
    6. GlorotNormal class  (Xavier normal initializer.)
    7. GlorotUniform class (Xavier uniform initializer.)
    8. Identity class
    9. Orthogonal class
    10.Constant class
    11.VarianceScaling class
    12.he_normal
    13.he_uniform
'''

In [5]:
import tensorflow as tf
tf.enable_eager_execution()

In [ ]:
# Example : Weights Initializer

my_init = tf.keras.initializers.RandomNormal(mean=0., stddev=1.)
model.add(layers.Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = my_init))

In [7]:
#01 : RandomNormal :Initializer that generates tensors with a normal distribution.
initializer = tf.keras.initializers.RandomNormal(mean=0., stddev=1.)

initializer(shape=(3,6))

<tf.Tensor: id=5, shape=(3, 6), dtype=float32, numpy=
array([[-1.0310596 ,  1.5364149 ,  0.47303712, -0.88736606, -0.7641309 ,
         0.41257107],
       [ 0.5381709 , -0.8736567 , -1.2155613 ,  0.54694617, -0.6089636 ,
        -0.02300584],
       [-1.0003396 , -0.9890549 ,  1.3654546 ,  0.31826758,  0.49240625,
         0.9720387 ]], dtype=float32)>

In [8]:
#02 : RandomUniform
# Initializer that generates tensors with a uniform distribution.

initializer = tf.keras.initializers.random_uniform(minval=0., maxval=1.)

initializer(shape=(3,6))

<tf.Tensor: id=12, shape=(3, 6), dtype=float32, numpy=
array([[0.32671952, 0.79163396, 0.9461535 , 0.8914664 , 0.3761419 ,
        0.35814357],
       [0.35890067, 0.3030846 , 0.37096226, 0.47756934, 0.02096701,
        0.6051339 ],
       [0.97108626, 0.23743224, 0.9348544 , 0.78687036, 0.1399343 ,
        0.31080306]], dtype=float32)>

In [9]:
#03 : TruncatedNormal

initializer = tf.keras.initializers.TruncatedNormal()

initializer(shape=(3,6))

<tf.Tensor: id=18, shape=(3, 6), dtype=float32, numpy=
array([[ 0.04547345,  0.04326083,  0.0769852 ,  0.0279826 ,  0.00513182,
         0.0660609 ],
       [-0.05027148,  0.03817039,  0.04294875, -0.01351773,  0.00666107,
        -0.06509379],
       [-0.08685701, -0.05917293,  0.01575092, -0.04980912,  0.01481654,
         0.05861143]], dtype=float32)>

In [10]:
#04 : Zeros

initializer = tf.keras.initializers.zeros()

initializer(shape=(3,6))

<tf.Tensor: id=21, shape=(3, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [11]:
#05 : Ones

initializer = tf.keras.initializers.ones()

initializer(shape=(3,6))

<tf.Tensor: id=24, shape=(3, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [12]:
#06 : GlorotNormal

initializer = tf.keras.initializers.glorot_normal()

initializer(shape=(3,6))

<tf.Tensor: id=30, shape=(3, 6), dtype=float32, numpy=
array([[-0.3185413 , -0.01064295,  0.00938116,  0.58327967, -0.81541115,
        -0.24442321],
       [-0.84178185,  0.25364095,  0.5016444 , -0.70472425,  0.11713209,
        -0.10989418],
       [-0.45341438,  0.7249815 ,  0.04862282, -0.17742807, -0.29592887,
         0.747353  ]], dtype=float32)>

In [13]:
#07 : GlorotUniform

initializer = tf.keras.initializers.glorot_uniform()

initializer(shape=(3,6))

<tf.Tensor: id=37, shape=(3, 6), dtype=float32, numpy=
array([[-0.58074844, -0.69644624,  0.7346399 ,  0.7052071 , -0.5048381 ,
        -0.71849024],
       [ 0.04205549,  0.43568242, -0.09827793, -0.22760946,  0.73631215,
        -0.2327137 ],
       [ 0.7179022 ,  0.65722215, -0.6060641 ,  0.52975845,  0.3723724 ,
        -0.33986592]], dtype=float32)>

In [14]:
#08 : Identity

initializer = tf.keras.initializers.identity()

initializer(shape=(4,8))

<tf.Tensor: id=46, shape=(4, 8), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [15]:
#08 : Orthogonal

initializer = tf.keras.initializers.Orthogonal()

initializer(shape=(4,8))

<tf.Tensor: id=63, shape=(4, 8), dtype=float32, numpy=
array([[ 0.07247651,  0.8170022 , -0.05767832,  0.18074252, -0.5151928 ,
        -0.039786  ,  0.09832843,  0.12076829],
       [ 0.17047   , -0.34085673, -0.16058342,  0.67189157, -0.39315596,
        -0.01723025, -0.13392815, -0.45246676],
       [-0.03346133,  0.29532835, -0.3474047 ,  0.24703555,  0.5763254 ,
        -0.59324366, -0.05244195, -0.20761931],
       [ 0.632659  ,  0.06590346,  0.00781837, -0.26534584, -0.02401462,
        -0.08783738, -0.7182016 ,  0.02870705]], dtype=float32)>

In [16]:
#09 : Constant
initializer = tf.keras.initializers.Constant(5)

initializer(shape=(4,8))

<tf.Tensor: id=66, shape=(4, 8), dtype=float32, numpy=
array([[5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5.]], dtype=float32)>

In [17]:
#10 : VarianceScaling

initializer = tf.keras.initializers.VarianceScaling()

initializer(shape=(4,8))

<tf.Tensor: id=72, shape=(4, 8), dtype=float32, numpy=
array([[-4.1177583e-01, -3.1345165e-01, -6.1062634e-01, -6.4900942e-04,
         4.1998184e-01, -8.5804111e-01,  5.1360000e-02, -3.4582719e-01],
       [-1.1966017e-01,  2.9372677e-01,  3.6936381e-01,  5.4440528e-02,
        -4.9286979e-01,  7.4837679e-01, -1.0651923e+00, -2.7565089e-01],
       [-2.1708006e-01, -8.6242408e-01,  1.4322816e-01,  5.3617960e-01,
         7.9573911e-01, -4.7770387e-01, -5.2943206e-01,  2.6865134e-01],
       [ 1.0990569e-01,  7.6171070e-02,  6.0751003e-01,  2.3259363e-01,
         1.6296567e-01, -5.0115740e-01,  3.2219689e-02, -3.2859299e-01]],
      dtype=float32)>

In [18]:
#11 : he_normal
initializer = tf.keras.initializers.he_normal()

initializer(shape=(4,8))

<tf.Tensor: id=78, shape=(4, 8), dtype=float32, numpy=
array([[-0.7735451 , -0.07514098,  0.33666918, -0.9048169 ,  0.01384004,
        -1.2124183 ,  1.0897499 , -0.459547  ],
       [-0.169464  , -0.27417454, -1.0095652 ,  0.6145237 ,  1.1939214 ,
        -0.18967956,  0.52161056, -0.05108817],
       [ 0.04995859, -0.80346   ,  0.3988812 ,  0.21657477,  0.6133422 ,
         0.05113552, -0.49075988, -0.13337655],
       [ 0.31305608,  0.6159353 ,  0.32717633,  0.67545545,  0.26182234,
         0.21326748,  0.955492  ,  0.27144736]], dtype=float32)>

In [19]:
#11 : he_uniform
initializer = tf.keras.initializers.he_uniform()

initializer(shape=(4,8))

<tf.Tensor: id=85, shape=(4, 8), dtype=float32, numpy=
array([[-0.85026383, -0.34127408,  1.2205335 , -0.48247743,  0.72737396,
         0.31863225, -0.7760217 ,  1.0700444 ],
       [-0.32959253,  1.0560695 ,  0.33362067,  0.99189556,  1.0493032 ,
        -1.0903125 , -0.73985904, -0.84375215],
       [ 1.2226111 ,  0.56347823,  0.854421  , -0.56699127,  0.7926854 ,
        -0.8180876 ,  0.73432446,  0.12601519],
       [ 0.3857062 , -0.7525679 , -0.92114615,  0.9350265 , -1.1278    ,
        -0.324686  ,  0.8916975 , -0.9309778 ]], dtype=float32)>

In [22]:
# How to set custom weights in keras using NumPy array


input_shape=(28,28,1)
model = tf.keras.Sequential(
    [
        tf.keras.Input(shape=input_shape,name='input'),
        tf.keras.layers.Conv2D(32, kernel_size=(3, 3),kernel_initializer=tf.keras.initializers.zeros(),
                               activation="relu",use_bias=True,name='conv1'),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(10, activation="relu",use_bias=True,bias_initializer='zeros',name='dense1'),
        tf.keras.layers.Dense(1, activation="softmax",name='output'),
    ]
)


In [31]:
model.layers[0].get_weights()[0]

array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.]]],


       [[[0., 0., 0., 0., 0., 

In [33]:
model.layers[0].get_weights()[0].shape

(3, 3, 1, 32)

In [36]:
import numpy as np

weights = np.random.rand(3,3,1,32)
bias = np.random.rand(32)

In [37]:
print(weights)

[[[[0.97253473 0.56416881 0.45968793 0.28722147 0.3568132  0.9696791
    0.62769849 0.50167025 0.49718229 0.05471336 0.11335707 0.61699172
    0.88619658 0.06657412 0.61719563 0.22836191 0.31016055 0.19599045
    0.66353198 0.68820417 0.16943112 0.25790905 0.62880501 0.02954975
    0.93791995 0.6891399  0.86994404 0.06198827 0.94320602 0.31539574
    0.79297276 0.84543336]]

  [[0.72127108 0.22413058 0.22816125 0.51208185 0.20789894 0.30069802
    0.32350273 0.21531742 0.41317838 0.6738812  0.41957319 0.10840429
    0.24383613 0.67184602 0.79487176 0.27924622 0.2182825  0.6327117
    0.54720373 0.61159282 0.93391689 0.08911895 0.82995932 0.84768953
    0.52101803 0.14089122 0.92273564 0.2964837  0.31301306 0.69305513
    0.99953875 0.93709514]]

  [[0.80115667 0.69454064 0.11059503 0.8377563  0.26888187 0.72723485
    0.61469569 0.51721557 0.90812622 0.92779313 0.8241409  0.37478044
    0.10906136 0.67485333 0.42307185 0.02347621 0.71089246 0.20400818
    0.22699792 0.84165731 0.802825

In [38]:
model.layers[0].set_weights([weights,bias])

In [39]:
model.layers[0].get_weights()[0]

array([[[[0.9725347 , 0.5641688 , 0.45968792, 0.28722146, 0.3568132 ,
          0.9696791 , 0.6276985 , 0.50167024, 0.49718228, 0.05471336,
          0.11335707, 0.6169917 , 0.88619655, 0.06657412, 0.6171956 ,
          0.2283619 , 0.31016055, 0.19599046, 0.66353196, 0.68820417,
          0.16943112, 0.25790906, 0.628805  , 0.02954976, 0.93792   ,
          0.6891399 , 0.86994404, 0.06198827, 0.943206  , 0.31539574,
          0.79297274, 0.84543335]],

        [[0.7212711 , 0.22413059, 0.22816125, 0.51208186, 0.20789894,
          0.300698  , 0.32350272, 0.21531741, 0.41317838, 0.6738812 ,
          0.4195732 , 0.10840429, 0.24383612, 0.67184603, 0.79487175,
          0.2792462 , 0.21828249, 0.6327117 , 0.5472037 , 0.6115928 ,
          0.93391687, 0.08911895, 0.82995933, 0.8476895 , 0.521018  ,
          0.14089121, 0.92273563, 0.2964837 , 0.31301305, 0.69305515,
          0.9995387 , 0.93709517]],

        [[0.8011567 , 0.6945406 , 0.11059503, 0.8377563 , 0.2688819 ,
          0.7272