In [ ]:
'''

Model API Overview

    - The Model Class
        - Model Class
        - summary
        - get_layer
    
    - Sequential Class
        - Sequential
        - add
        - pop
    
    - Model training
        - compile 
        - fit
        - evaluate
        - predict
        - train_on_batch
        - test_on_batch
        - predict_on_batch
        - run_eagrely
        
    - Model saving & serialization
        - save model
        - load model
        - get_weights
        - set_weights
        - save_weights
        - load_weights
        - get_config
        - from_config
        - model_from_config
        - to_json
        - model_from_json
        - clone_model
    
'''

In [8]:
'''
Model : Model groups layers into an object with training and inference features.
   
tf.keras.Model()

    Arguments 
        - inputs
        - outputs
        - name
        
Ways of  Models can be instantiated:
    - Functional API
    - subclassing 
'''

# Example using Functional API

import tensorflow as tf

inputs = tf.keras.Input(shape=(3,))

x = tf.keras.layers.Dense(4, activation=tf.nn.relu,name="l1")(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

In [9]:
# Print Model Summary

model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
l1 (Dense)                   (None, 4)                 16        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 25        
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [13]:
# get_layer and get weights

model.get_layer('l1').get_weights()

[array([[-5.4009080e-02,  5.7458210e-01, -2.7516484e-03,  9.0599191e-01],
        [ 1.6134977e-04, -1.2369752e-03,  9.7188592e-02, -1.8547463e-01],
        [ 5.4360723e-01, -4.7398642e-01,  8.3838809e-01,  1.9523871e-01]],
       dtype=float32), array([0., 0., 0., 0.], dtype=float32)]

In [ ]:
'''
  Types of Keras Models Creation
    -  Sequential Model
            - The Sequential model is a linear stack of layers.
            - Passing a list of layers to the constructor
            - Simply add layers via the .add() method:
    -  Functional API
            - It allows us to define multiple input or output models as well as models that share layers.
            - Input() is used to define the input layer with input shape as an argumentshape=(4,)
            - Only things we need to reference in Model() are the inputs and outputs tensors
    -  Sub Classing
            - Implement everything from scratch on your own
            - Use this if you have complex, out-of-the-box research use cases.
'''

In [ ]:
'''

When to use Sequential Model

A Sequential model is appropriate for a plain stack of layers where each layer has exactly one input and one output

A Sequential model is not appropriate 
    - Your model has multiple inputs or multiple outputs
    - Any of your layers have multiple inputs or multiple outputs
    - You need to do layer sharing
    - You want non-linear topology (e.g. a residual connection, a multi-branch model)
    
'''

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

In [17]:
# Sequential Model  : Linear Stack of layer

model = Sequential([Dense(32,input_shape=(784,)),Activation('relu'), Dense(10),Activation('softmax')])

#or

model = Sequential()

model.add(Dense(32,input_shape=(784,)))
model.add(Activation('relu'))
model.add(Dense(10))
model.add(Activation('softmax'))

In [19]:
# get unmber of layers in in the model

len(model.layers)

4

In [20]:
# add method : Adds a layer instance on top of the layer stack.

model.add(Dense(10))

In [22]:
# pop method : Removes the last layer in the model

model.pop()

In [23]:
# get unmber of layers in in the model

len(model.layers)

4

In [2]:

import numpy as np
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense


In [6]:
# Functional API : Exmaple

data = np.random.random((1000, 100))
labels = np.random.randint(10, size=(1000, 1))

# Convert labels to categorical one-hot encoding
one_hot_labels = to_categorical(labels, num_classes=10)

inputs = Input(shape=(100,))
output_1 = Dense(32, activation='relu')(inputs)
predictions = Dense(10, activation='relu')(output_1)

model = Model(inputs=inputs, outputs=predictions) # Model API Used when Function al API are Used

# Compile
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

# Train the model, iterating on the data in batches of 32 samples
model.fit(data, one_hot_labels, epochs=10, batch_size=32)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 1000 samples
Epoch 1/10
1000/1000 [==============================] - 0s 337us/sample - loss: 5.5926 - acc: 0.0970
Epoch 2/10
1000/1000 [==============================] - 0s 77us/sample - loss: 3.7449 - acc: 0.1000
Epoch 3/10
1000/1000 [==============================] - 0s 74us/sample - loss: 3.6562 - acc: 0.1010
Epoch 4/10
1000/1000 [==============================] - 0s 70us/sample - loss: 3.6326 - acc: 0.1110
Epoch 5/10
1000/1000 [==============================] - 0s 70us/sample - loss: 3.6255 - acc: 0.1150
Epoch 6/10
1000/1000 [==============================] - 0s 73us/sample - loss: 3.6202 - acc: 0.1260
Epoch 7/10
1000/1000 [==============================] - 0s 73us/sample - loss: 3.6139 - acc: 0.1260
Epoch 8/10
1000/1000 [==============================] - 0s 81us/sample - loss: 3.6045 - acc: 0.1190
Epoch 9/10
1000/1000 [==============================] - 0s 79us/sample - loss: 3.60

In [ ]:
'''
Life Cycle of Model Creation in Keras

Model Creation --> Model Compilation ---> Model Fit--> Evaluate Network --> Model Predict
'''

In [ ]:
'''
# Interpretign the Model

model = Sequential() 
model.add(Dense(512, activation = 'relu', input_shape = (784,))) 
model.add(Dropout(0.2)) 
model.add(Dense(512, activation = 'relu'))
model.add(Dropout(0.2)) 
model.add(Dense(10, activation = 'softmax'))

# Compile Model
model.compile(loss = 'categorical_crossentropy',optimizer = RMSprop(), metrics = ['accuracy'])

# Training Model
history = model.fit(x_train, y_train, batch_size = 128, epochs = 20, verbose = 1, validation_data = (x_test, y_test))

1. Input layer consists of 784 values (28 x 28 = 784).
2. First hidden layer, Dense consists of 512 neurons and ‘relu’ activation function.
3. Second hidden layer, Dropout has 0.2 as its value.
4. Third hidden layer, again Dense consists of 512 neurons and ‘relu’ activation function.
5. Fourth hidden layer, Dropout has 0.2 as its value.
6. Fifth and final layer consists of 10 neurons and ‘softmax’ activation function.
7. Use categorical_crossentropy as loss function.
8. Use RMSprop() as Optimizer.
9. Use accuracy as metrics.
10. Use 128 as batch size.
11. Use 20 as epochs.

'''

In [15]:
# Add Layer

# You can also simply add layers via the .add() method

model = Sequential()
model.add(Dense(32,input_dim=784))
model.add(Activation('relu'))


In [16]:
# Compilation : Before training a model, you need to configure the learning process, which is done via the compile method. 
# It receives three arguments:

# For a multi-class classification problem
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [17]:
model.layers[0].get_weights()[0].shape  # weight siz of (784,32) 

(784, 32)

In [18]:
# Get Model Summary

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(8,input_shape=(10,),activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(1,activation='linear'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 8)                 88        
_________________________________________________________________
dense_12 (Dense)             (None, 4)                 36        
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 5         
Total params: 129
Trainable params: 129
Non-trainable params: 0
_________________________________________________________________


In [19]:
# Get the shape of Layer 0

model.layers[0].get_weights()[0].shape 

(10, 8)

In [20]:
# Get the share of output layer

model.layers[2].get_weights()[0].shape 

(4, 1)

In [21]:
model.layers[2].get_weights()

[array([[ 0.84960663],
        [-0.20277429],
        [-0.86632174],
        [ 0.5413501 ]], dtype=float32), array([0.], dtype=float32)]

In [ ]:
'''
Specifying the Input Shape

01 using input_shape

Example

''''

model = Sequential()
model.add(Dense(32, input_shape=(784,)))


'''
02 using input_dim

Example

'''

model = Sequential()
model.add(Dense(32, input_dim=784))


In [ ]:
'''
Model creation with Weight Initializer (Kernel Initilizer)

'''

#Initialize
model = Sequential()

my_init = initializers.Zeros() 
model.add(layers.Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = my_init))


# Other types of Initilzers

initializers.Ones() 
initializers.Constant(value = 5)
initializers.RandomNormal(mean=0.0, stddev = 0.05, seed = None) 
initializers.RandomUniform(minval = -0.05, maxval = 0.05, seed = None)
initializers.TruncatedNormal(mean = 0.0, stddev = 0.05, seed = None)
initializers.VarianceScaling(scale = 1.0, mode = 'fan_in', distribution = 'normal', seed = None) 

#...etc

In [ ]:
'''
Model Creation with Regularization

Different Types of Regularization
    1. L2 and L1 regularization
    2. Dropout
    3. Data augmentation
    4. Early stopping
'''

from tensorflow.keras import regularizers

# Define l1 Regularizer
my_regularizer = regularizers.l1(0.)

model = Sequential()
model.add(layers.Dense(512,activation='relu',input_shape=(784,),kernel_regularizer=my_regularizer))

# Other Regularizers

my_regularizer = regularizers.l2(0.)
my_regularizer = regularizers.L1L2(0.0,0.0)
 


In [ ]:
'''
Model Creation with Activation Function

'''

# Initialize Model
model = Sequential() 

# 01 Linear
model.add(layers.Dense(512,activation='linear',input_shape=(784,)))

# 02 elu (Exponential linear unit.)
model.add(layers.Dense(512,activation='elu',input_shape=(784,)))

# 04 relu(Rectified Linear Unit.)
model.add(layers.Dense(512,activation='relu',input_shape=(784,)))

# 05 Softmax
model.add(layers.Dense(512,activation='softmax',input_shape=(784,)))

#...etc


In [ ]:
'''
Model Creation Last Layer Activation and Loss Function bases on the use case

'''

model = Sequential()

#01 Binary classification - Dog VS Cat

    model.add(Dense(1,activation = 'sigmoid'))
    model.compile(optimizer = optimizers.RMSprop(lr=1e-4), loss='binary_crossentropy',metrics=['acc'])

#02 Multi-class single-label classification - MNIST

    model.add(layers.Dense(10, activation='softmax'))
    model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

#03 Regression to arbitrary values - Bosten Housing price prediction

    model.add(layers.Dense(1))
    model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])

#04 Regression to values between 0 and 1

    model.add(layers.Dense(1, activation='sigmoid'))
    model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])

In [ ]:
'''
Model with 2 inputs and 1 output

'''

from tensorflow.keras.layers import concatenate

input_structure = Input(shape=(4,), name='input_structure')
input_image = Input(shape=(256,), name='input_image')

# middle layers
x_1 = Dense(10, activation='relu')(input_structure)
x_2 = Dense(100, activation='relu')(input_image)

c = concatenate([x_1, x_2])

outputs = Dense(3, activation='sigmoid', name='outputs')(c)

model = Model(inputs=[input_structure, input_image], outputs=outputs)

In [ ]:
'''
Model with 1 input and 2 outputs

'''

from tensorflow.keras.layers import concatenate

# only one input
input_image = Input(shape=(256,), name='input_image')

# middle layer
x = Dense(300, activation='relu')(input_image)

# output layser
output_1 = Dense(1, activation='sigmoid', name='output_1')(x)
output_2 = Dense(3, activation='softmax', name='output_2')(x)

model = Model(inputs=input_image, outputs=[output_1, output_2])


In [ ]:
'''
Model with 2 inputs and 2 outputs.

'''

from tensorflow.keras.layers import concatenate

# 2 inputs, one structured data, the other image data
input_structured = Input(shape=(4,), name='input_structured')
input_image = Input(shape=(256,), name='input_image')

# middle layers
x_1 = Dense(10, activation='relu')(input_structure)
x_2 = Dense(300, activation='relu')(input_image)

c = concatenate([x_1, x_2])

# output layser
output_1 = Dense(1, activation='sigmoid', name='output_1')(c)
output_2 = Dense(3, activation='softmax', name='output_2')(c)

model = Model(inputs=[input_structured, input_image], outputs=[output_1, output_2])


In [ ]:
'''
Model with Cross Validation using 'KerasClassifier'
'''

# Create Function that constructs a neural network
def create_network():
    
    network = Sequential()
    network.add(Dense(units =16,activation='relu',input_shape = (100,)))
    network.add(Dense(units=16,activation='relu'))
    network.add(Dense(units=1,activation = 'sigmoid'))
    network.compile(loss='binary_crossentropy',optimizer='rmsprop',metrics=['accuracy'])
    
    return network
    
# Wrap Function In KerasClassifier
neural_network = KerasClassifier(build_fn=create_network,epochs = 10,batch_size=100,verbose=0)

# Conduct k-Fold Cross-Validation Using scikit-learn
# Evaluate neural network using three-fold cross-validation
cross_val_score(neural_network, features, target, cv=3)


In [ ]:
'''
Model with 'Grid Search CV' for hyperparamter Tuning
'''

from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

# Create Function that constructs a neural network and takes optimiser as parameter
def build_classifers(optimizer):
    model = Sequential()
    model.add(Dense(units =6, kernel_initializer = 'uniform',activation='relu',input_dim=12))
    model.add(Dense(units =6,kernel_initializer = 'uniform',activation='relu'))
    model.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))
    model.compile(optimizer=optimizer,loss = 'binary_crossentropy',metrics = ['accuracy'])
    return model
    
# Wrap Function In KerasClassifier
classier =KerasClassifier(build_fn=build_classifers)

# Hyper parameters 
parameters = {'batch_size': [25,32],'epochs':[1,2],'optimizer':['adam','rmsprop']}

# Define Grid Seach CV
grid_search = GridSearchCV(estimator=classier,param_grid=parameters,scoring='accuracy',cv=10)

# Fit the Data
grid_search = grid_search.fit(X_train,y_train)

# Get the Best Parameters
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_


In [ ]:
'''
Model with 'Grid Search CV' for hyperparamter Tuning for finding Activation function

'''

# Create Function that constructs a neural network and takes optimiser as parameter
def create_model(activation='relu'):
    # create model
    model = Sequential()
    model.add(Dense(12, input_dim=8, kernel_initializer='uniform', activation=activation))
    model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
    
# Wrap Function In KerasClassifier
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)

# define the grid search parameters
activation = ['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear']
param_grid = dict(activation=activation)

# Define Grid Seach CV
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)

# Fit the Data
grid_result = grid.fit(X, Y)   

# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

In [ ]:
'''
Model Subclassing
'''

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense
class CustomModel(Model):
    
    def __init__(self, **kwargs):
        super(CustomModel, self).__init__(**kwargs)
        self.dense1 = Dense(5, activation='relu', )
        self.dense2 = Dense(10, activation='relu')
        self.dense3 = Dense(3, activation='softmax')
        
    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        return self.dense3(x)
    
my_custom_model = CustomModel(name='my_custom_model')

# Training a Model Subclassing model
my_custom_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

history = my_custom_model.fit(X_train, y_train,batch_size= 64,epochs= 30,validation_split=0.2)

In [ ]:
'''
Drop outs:

Dropout is a regularization technique to prevent overfitting in a neural network model training

The method randomly drops out or ignores a certain number of neurons in the network.

How to use Dropout layer in Keras model
    1. After the input layer
    2. Between the hidden layers
    3. Before the output layer
    
    
# 1. After the input layer

model = Sequential()
model.add(Dense(16, input_dim=4, activation="relu")) 
model.add(Dropout(0.2))


# 2. Between the hidden layers

model.add(Conv2D())
model.add(MaxPooling())
model.add(Dropout(0.2)

# 3. Before the output layer

model.add(Dropout(0.2))
model.add(Dense(3, activation="softmax"))

'''

In [26]:
'''
Simple Linear Regression
'''

import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import RMSprop

df = pd.read_csv("C:\MyWork\MyLearning\Career Growth\ML\Files\DataSet\Linear-Regression-Data.csv")

x = df.x
y = df.y

print(df)

# Define Model
model = Sequential()

# Add Model Layer
model.add(Dense(32,activation='relu',input_dim=1))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,))

# Compile Model
optimizer = RMSprop(0.0099)

model.compile(optimizer=optimizer,loss='mean_squared_error')
model.fit(x,y,epochs=500,verbose=0)

# Predict
model.predict([200])

       x       y
0      0  -17.78
1      1  -17.22
2      2  -16.67
3      3  -16.11
4      4  -15.56
..   ...     ...
995  995  535.00
996  996  535.56
997  997  536.11
998  998  536.67
999  999  537.22

[1000 rows x 2 columns]


array([[93.64606]], dtype=float32)

In [27]:
'''
Save and Load the Keras Model

'''
# serialize model to JSON
model_json = model.to_json()

with open("model.json", "w") as json_file:
    json_file.write(model_json)

# serialize weights to HDF5
model.save_weights("model.h5")    # Save weights
print("Saved model to disk")

In [ ]:
# load json and create model

json_file = open('model.json', 'r')

loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

# load weights into new model
loaded_model.load_weights("model.h5")  # load_weights
print("Loaded model from disk")

# evaluate loaded model on test data
loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
score = loaded_model.evaluate(X, Y, verbose=0)

In [29]:
# serialize model to YAML

model_yaml = model.to_yaml()
with open("model.yaml", "w") as yaml_file:
    yaml_file.write(model_yaml)
    
# serialize weights to HDF5
model.save_weights("model.h5")  # Save weights
print("Saved model to disk")


Saved model to disk


In [ ]:
from keras.models import model_from_yaml

# load YAML and create model
yaml_file = open('model.yaml', 'r')
loaded_model_yaml = yaml_file.read()

yaml_file.close()

loaded_model = model_from_yaml(loaded_model_yaml)
# load weights into new model
loaded_model.load_weights("model.h5")  # load_weights
print("Loaded model from disk")

# evaluate loaded model on test data

loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
score = loaded_model.evaluate(X, Y, verbose=0)

In [32]:
'''
Save Model Weights and Architecture Together
  - Saving the model in this way includes everything we need to know about the model, including
    - Model weights.
    - Model architecture.
    - Model compilation details (loss and metrics).
    - Model optimizer state.

'''

# save model and architecture to single file

model.save("model.h5")
print("Saved model to disk")

# Load the Keras model : The function returns the model with the same architecture and weights
from keras.models import load_model
 
# load model
model = load_model('model.h5')

Saved model to disk


In [ ]:
'''
Note : Difference betweeen 'model.save_weights()' and 'mode.save()'

model.save_weights() :will only save the weights so if you need, you are able to apply them on a different architecture

mode.save() will save the architecture of the model + the the weights + the training configuration + the state of the optimizer

'''

In [35]:
# get Weight

import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
import matplotlib.pyplot as plt

x = np.random.randn(100)
y = x*3 + np.random.randn(100)*0.8

model = Sequential()
model.add(Dense(4, input_dim = 1, activation = 'linear', name = 'layer_1'))
model.add(Dense(1, activation = 'linear', name = 'layer_2'))
model.compile(optimizer = 'sgd', loss = 'mse', metrics = ['mse'])

In [36]:
'''
get_weight : get the weights and biases of the layers before training the model.

'''

for layer in model.layers:
  print(layer.name)
  print("Weights")
  print("Shape: ",layer.get_weights()[0].shape,'\n',layer.get_weights()[0])
  print("Bias")
  print("Shape: ",layer.get_weights()[1].shape,'\n',layer.get_weights()[1],'\n')

layer_1
Weights
Shape:  (1, 4) 
 [[-0.4659645   1.0331597   0.545838   -0.58148044]]
Bias
Shape:  (4,) 
 [0. 0. 0. 0.] 

layer_2
Weights
Shape:  (4, 1) 
 [[0.13917828]
 [0.28758729]
 [0.6175275 ]
 [0.25251186]]
Bias
Shape:  (1,) 
 [0.] 



In [38]:
'''
set_weights() : setting custtom weights for the layers in the Models

'''

# Setting new weights and biases
for layer in model.layers:
  a,b = layer.get_weights()[0].shape
  layer.set_weights([np.random.randn(a,b), np.ones(layer.get_weights()[1].shape)])
    
    
print("Weights and biases of the layers after setting the new weights and biases: \n")
for layer in model.layers:
  print(layer.name)
  print("Weights")
  print("Shape: ",layer.get_weights()[0].shape,'\n',layer.get_weights()[0])
  print("Bias")
  print("Shape: ",layer.get_weights()[1].shape,'\n',layer.get_weights()[1],'\n')

Weights and biases of the layers after setting the new weights and biases: 

layer_1
Weights
Shape:  (1, 4) 
 [[ 0.5767459   0.01784462  0.35760444 -0.9040189 ]]
Bias
Shape:  (4,) 
 [1. 1. 1. 1.] 

layer_2
Weights
Shape:  (4, 1) 
 [[-0.2023459 ]
 [ 0.46942163]
 [-1.0108349 ]
 [ 1.7490941 ]]
Bias
Shape:  (1,) 
 [1.] 



In [ ]:
'''
get_config

'''

In [ ]:
'''
from_config

'''

In [ ]:
'''
model_from_config

'''

In [ ]:
'''
clone_model

'''