In [1]:
# Sequence : Order

# Sequence Prediction Problems :

1. Sequence Prediction : Predicting next value for a given input sequence
        Ex: Input Sequence : 12345 Output Sequence : 6
            
2. Sequence Classification : Predicting class label for a given input sequence
        Ex: Input Sequence : 12345 Output Sequence : "Good" or "Bad"

3. Sequence Generation :generating a new output sequence that has the same general characteristics 
                        as other sequences in the corpus
        Ex: Input Sequence: [1, 3, 5], [7, 9, 11] Output Sequence: [3, 5 ,7]
                    
4. Sequence-to-Sequence Prediction : Predicting an output sequence given an input sequence
        Ex: Input Sequence: 1, 2, 3, 4, 5 Output Sequence: 6, 7, 8, 9, 10

In [ ]:
1.Sequence Prediction Probelms :
    1. Weather Forecasting
    2. Stock market Prediction
    3. Product Recommendation
    
2.Sequence Classification :
    1. DNA Sequence Classification :Given a DNA sequence of A, C, G, and T values, predict whether the sequence 
                                    is for a coding or non-coding region
            
    2. Anomaly Detection : Given a sequence of observations, predict whether the sequence is anomalous or not
        
    3. Sentiment Analysis : Given a sequence of text such as a review or a tweet, predict whether the sentiment 
                            of the text is positive or negative          
3.Sequence Generation : 
    1. Text Generation 
    2. Handwriting Prediction.
    3. Music Generation
    4. Image Caption Generation : Input Sequence: [image pixels] Output Sequence: ["man riding a bike"]
                

4.Sequence-to-Sequence Prediction :
    1. Multi-Step Time Series Forecasting
    2. Text Summarization
    3. Program Execution.
    

In [ ]:
Backpropagation Training Algorithm :
    
    1. The mathematical method used to calculate derivatives and an application of the derivative chain rule.
    2. The training algorithm for updating network weights to minimize error

In [ ]:
Steps Followed in the General Algorithms

1. Present a training input pattern and propagate it through the network to get an output
2. Compare the predicted outputs to the expected outputs and calculate the error
3. Calculate the derivatives of the error with respect to the network weights.
4. Adjust the weights to minimize the error
5. Repeat

In [ ]:
# Prepare Data for LSTM

1. Numeric Data : Data needs to be scaled when training a neural network

2. Categorical Data : Convert Categorical Data to Numerical Data
       - Integer Encoding
       - One Hot Encoding

3. Sequences with Varied Lengths
       - Sequence Padding
            - Pre-Sequence Padding
            - Post-Sequence Padding
       - Sequence Truncation
            - Pre-Sequence Truncation
            - Post-Sequence Truncation

In [20]:
# For Seqeunce data preparing input and output column use pandas shift()

from pandas import DataFrame
# define the sequence
df = DataFrame()
df['t'] = [x for x in range(10)]
# print(df)

# Shift Fowrds
df['t-1'] = df['t'].shift(1)

# Shift backward
df['t+1'] = df['t'].shift(-1)

print(df)

   t  t-1  t+1
0  0  NaN  1.0
1  1  0.0  2.0
2  2  1.0  3.0
3  3  2.0  4.0
4  4  3.0  5.0
5  5  4.0  6.0
6  6  5.0  7.0
7  7  6.0  8.0
8  8  7.0  9.0
9  9  8.0  NaN


In [26]:
#  Define the Model 

Neural net works in keras as sequence of layers,The container for these layers is the Sequential class.


1. Create an instance of the Sequential class (container for layers)
2. Create multiple layers and add them in the order that they should be connected.(Ex LSTM Layer)
3. Dense is fully connected layer that often follows LSTMlayers used for outputting a prediction


*************************************************************************************************************
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM,Dense

# 01 : One Way of Creating
# we can define an LSTM hidden layer with 2 memory cells followed by a Dense output layer with 1 neuron
model = Sequential()
model.add(LSTM(2))
model.add(Dense(1))

#02 : creating an array of layers and passing it to the constructor of the Sequential class
layers = [LSTM(2), Dense(1)]
model = Sequential(layers)
*************************************************************************************************************


# Input : Input must be three-dimensional (Samples,Time Step, Features)

# Activation Functions :
    Regression: Linear activation function
    Binary Classification : sigmoid
    Multiclass Classification : Softmax

In [ ]:
# Evaluate the Model

Once the network is trained, it can be evaluated

# Predict the Model
Predict model is calling the predict() function on the model with an array of new input patterns.

In [29]:
# LSTM State Management 

In [ ]:
# Preparing Data for LSTM

1. The LSTM input layer must be 3D.
2. The meaning of the 3 input dimensions are: samples, time steps and features.
3. The reshape() function on NumPy arrays can be used to reshape your 1D or 2D data to be 3D.
4. The reshape() function takes a tuple as an argument that defines the new shape

In [ ]:
# One-to-One (Multiple Features)

X = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

X = array(X).reshape(20, 1, 1)

model.add(LSTM(50, activation='relu', input_shape=(1, 1)))  # input_shape=(1 time_step,2 features)

In [ ]:
# One-to-One (Multiple Features)

X1 = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
X2 = [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75]

X = np.column_stack((X1, X2))

X = array(X).reshape(25, 1, 2) # convert the input into 3-dimensional shape

model.add(LSTM(80, activation='relu', input_shape=(1, 2))) # input_shape=(1 time_step,2 features)

In [ ]:
# Many-to-One Sequence (Single Feature)

X = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,
     36,37,38,39,40,41,42,43,44,45]

y = [6,15,24,33,42,51,60,69,78,87,96,105,114,123,132]

X = X.reshape(15,3,1)

model.add(LSTM(50, activation='relu', input_shape=(3, 1))) # input_shape=(3 time_step,1 features)

In [ ]:
# Many-to-One Sequence (Multiple Feature)

X1  = [3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90,93,
       96,99,102,105,108,111,114,117,120,123,126,129,132,135]

X2  = [5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130,135,
       140,145,150,155,160,165,170,175,180,185,190,195,200,205,210,215,220,225]

y = [24,48,72,96,120,144,168,192,216,240,264,288,312,336,360]

X = np.column_stack((X1, X2))

X = array(X).reshape(15, 3, 2)

model.add(LSTM(50, activation='relu', input_shape=(3, 2))) # input_shape=(3 time_step,2 features)

In [ ]:

from numpy import array

data = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

data = data.reshape((1, 10, 1)) # 1 sample,10 time steps, and 1 features

model.add(LSTM(32, input_shape=(10, 1))) # input_shape=(10 time_step, 1 features)

In [ ]:
from numpy import array
X = array([[0.1, 1.0],[0.2, 0.9],[0.3, 0.8],[0.4, 0.7],[0.5, 0.6],[0.6, 0.5],[0.7, 0.4],[0.8, 0.3],[0.9, 0.2],[1.0, 0.1]])

# 1 sample with 10 time steps and 2 features.
X = X.reshape(1, 10, 2)

model.add(LSTM(32, input_shape=(10, 2)) # input_shape=(10 time_step, 2 features)

In [ ]:
# Example :

# Generated sequences as follows

# One Sample Input Sequence in raw format:
X[0]=[5, 0, 9, 9]

# One Hot Encoding

5 : [0 0 0 0 0 1 0 0 0 0]
0 : [1 0 0 0 0 0 0 0 0 0]
9 : [0 0 0 0 0 0 0 0 0 1]
9 : [0 0 0 0 0 0 0 0 0 1]

# In one_hot_encoded format:  # (1,4,10) (1 Sample ; 4 time steps ; 10 feaures)

X[0]=[[0 0 0 0 0 1 0 0 0 0],
      [1 0 0 0 0 0 0 0 0 0],
      [0 0 0 0 0 0 0 0 0 1],
      [0 0 0 0 0 0 0 0 0 1]]

# Shape of an input to LSTM (X[0].shape):  (1, 4, 10)

In [31]:
# Example 2:

# embedding of the Characters in the string : for LSTM

import numpy as np

word_vec_length = 10 # maximum length of the name

char_to_int = {'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 
               'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 
               'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 
               'w': 22, 'x': 23, 'y': 24, 'z': 25, 'ö': 26, 'ä': 27, 'ü': 28,
               '-': 29, 'ß': 30, ' ': 31}

char_vec_length = len(char_to_int)


# Returns a list of n lists with n = word_vec_length
def name_encoding(name):

    # Encode input data to int, e.g. a->1, z->26
    integer_encoded = [char_to_int[char] for i, char in enumerate(name) if i < word_vec_length]
    
    # Start one-hot-encoding
    onehot_encoded = list()
    
    for value in integer_encoded:
        # create a list of n zeros, where n is equal to the number of accepted characters
        letter = [0 for _ in range(char_vec_length)]
        letter[value] = 1
        onehot_encoded.append(letter)
        
    # Fill up list to the max length. Lists need do have equal length to be able to convert it into an array
    for _ in range(word_vec_length - len(name)):
        onehot_encoded.append([0 for _ in range(char_vec_length)])
        
    return onehot_encoded

names = ['santhosh','anand','sachin','prashanth']

# use asarray to use change the shape of the array which suits for LSTM
enc = np.asarray([np.asarray(name_encoding(name)) for name in names])

print(enc.shape)

# Batch_size(Samples) : 4  : ['santhosh','anand','sachin','prashanth']
# time_step : 10 :  max length of the sentence 
# features : 32 :  Length of the Vocabulary

(4, 10, 32)


In [32]:
print(enc[0]) # First Sample Data # Row(time_step) : 10 and Column(Features) :32

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [33]:
print(enc[3]) # Forth Sample Data # Row(time_step) : 10 and Column(Features) :32

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [34]:
# One Hot Encoding Creation machanisam for LSTM

names = ["santhosh","kumar","anand","joshi"] # Samples

import string 

# get the alphabest
string.ascii_lowercase

# List of Vocabulary
vocabs_ = [x for x in string.ascii_lowercase] # Features

# vocabulary length
vocab_length = len(string.ascii_lowercase)

# Max Sequence Length
max_seq_length = max([len(x) for x in names])

char_2_int = {} 
int_2_char = {}

# Char to Interger 
char_2_int = dict([(x,i) for i,x in enumerate(vocabs_)])

# Integer to Char
int_2_char = dict([(i,x) for i,x in enumerate(vocabs_)])

# Create Zero array for encoding

encoding = np.zeros((len(names),max_seq_length,vocab_length))

print(encoding.shape)  # (4 Samples,max length of samples,vocabulary Length

# Update the encoder matrix for the samples

for i,name in enumerate(names): # i = index value and i = sample and j =time step
    for j,char in enumerate(name):
        encoding[i,j,char_2_int[char]] = 1.0
        
encoding

(4, 8, 26)


array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0

In [ ]:
# Mapping Application to Model

1. Univariate Time Series Forecasting
    Input : Multiple input time steps
    Output : one time step
    Model : Many-To-One model (Single Feature)
        
2. Multivariate Time Series Forecasting
    Input : Multiple series with multiple input time steps
    Output : one time step
    Model : many-to-one model (Multiple Features)
        
3. Multi-step Time Series Forecasting
   Input : One or Multiple series with multiple input time steps
   Output : Multiple time steps
   Model : many to Many Model

4. Time Series Classification
   Input : Multiple series with multiple input time steps
   Output : Classification Label
   Model : many to many Model
    
5. Image Captioning
   Input : one image
   Output : Textual description.
   Model : One to many Model

6. Sentiment Analysis
   Input : sequences of text
   Output : classification label 
   Model : Many to One Model

7. Speech Recognition
   Input : Sequence of audio data
   Output : Generate a textual description
   Model : Many to Many Model

8. Text Translation
   Input : Sequence of words in one language
   Output : sequence of words in another language
   Model : Many to Many model

8. Text Summarization
   Input : Document of text
   Output : Short textual summary of the document
   Model : Many To Many

In [ ]:
# Different LSTMs Architectures

# 01 Vanilla LSTMs : Memory cells of a single LSTM layer are used in a simple network structure.
    
Vanilla LSTM consists of:
    1. Input Layer
    2. Fully Connected LSTM Hidden Layer
    3. Fully Connected output layer

In [ ]:
# 02 Stcked LSTM

The Stacked LSTM is a model that has multiple hidden LSTM layers where each layer contains multiple memory cells.

In [ ]:
# 04 Encoder and Decoder LSTMs : 

One LSTM network encodes input sequences and a separate LSTM network decodes the encoding into an output sequence

The encoder-decoder model is a way of organizing recurrent neural networks for sequence-to-sequence prediction problems.

# Architecture of Encoder decoder LSTM

Input--> Encoder Model-->Decoder Model-->Dense-->output

# Application
    - Machine Translation
    - Learning To Execute
    - Image Caption
    - Conversational Modeling
    - Movement Classification
    
The approach involves two recurrent neural networks, 
    1. one to encode the source sequence, called the encoder, 
    2. second to decode the encoded source sequence into the target sequence, called the decoder.
    

In [ ]:
# Life Cycle of LSTM :

In [ ]:
# Different Types of LSTM Architectures

In [2]:
# Stacked LSTMs : LSTM layers are stacked one on top of another into deep networks

In [5]:
# Bidirectional LSTMs : Input sequences are presented and learned both forward and backward.

In [ ]:
# Generative LSTM : LSTMs learn the structure relationship in input sequences so well that they 
#                   can generate new plausible sequences

In [6]:
# Diagnose and Tune LSTMs

In [7]:
# Update LSTM Models for New Data