In [2]:
# Sequence Porblem brodly Categories into the following categories

# 1. One-to-One : Where there is a one input and one output. 
# Example : where you have a image and you want to predict a single label for the image

# 2. Many-to-One : We have sequence of data as input and we have to predict a single output.
# Example : Text classification is a primary example of many to one sequence example 

#3. One-to-Many : We have Single input and many a sequence of outputs.
# Example : image and its corresponding description

#4. Many-to-Many : It involves sequecne of input and a sequence of output.
#Example : Stock price of 7 days as input and stock price of next 7 days as output
# Charbot is also an exmple for Many to Many sequence problem where a text sequecne is an input and another text sequence is 
# the output

In [3]:
# One-to-one Sequence : One Time-step and One Output
# X = [1,2,3,4,5,6,7,8,9]
# Y = (X *15)
# Y = [15, 30, 45, 60, 75, 90, 105, 120, 135]

import numpy as np

X = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])
Y = np.array([[15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300]])

X = X.reshape(20,1,1) # 20 Samples; 1 Time step; 1 Feature

print(X[:3])

[[[1]]

 [[2]]

 [[3]]]


In [4]:
# One-To-One Sequence using Multiple Feature

X = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])
Y = np.array([[3,7,11,15,19,23,27,31,35,39]])

X = X.reshape(10,1,2) # 10 Sample; Time Step =1 and Feature =2 

print(X)

[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]

 [[11 12]]

 [[13 14]]

 [[15 16]]

 [[17 18]]

 [[19 20]]]


In [26]:
# One-to-many Sequence

# Use case : Predict the previous Index numbers
# Ex [0 = -2,-1,0], [1 = -1,0,1], [2 = 0,1,2],  [3 = 1,2,3] [4 = 2,3,4] [5 = 3,4,5]

X : np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Y = np.array([[-2,-1,0],[-1,0,1],[0,1,2],[1,2,3],[2,3,4],[3,4,5],[5,6,7],[6,7,8],[6,7,8],[7,8,9]])

In [45]:
# Many-to-One Sequence : time-step =2 or Many and Output =1
# X = [1+2+3];[4+5+6];[7+8+9]
# Y = 6;     15;    24

X = np.array([[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,
               34,35,36,37,38,39,40,41,42,43,44,45]])

Y = np.array([6,15,24,33,42,51,60,69,78,87,96,105,114,123,132])

X = X.reshape(15,3,1) # 15 Sample; Time Step =3 and Feature =1

X[:3]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])