In [ ]:
# One-to-One (Multiple Features)

X = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

X = array(X).reshape(20, 1, 1)

model.add(LSTM(50, activation='relu', input_shape=(1, 1)))  # input_shape=(1 time_step,2 features)

In [ ]:
# One-to-One (Multiple Features)

X1 = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
X2 = [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75]

X = np.column_stack((X1, X2))

X = array(X).reshape(25, 1, 2) # convert the input into 3-dimensional shape

model.add(LSTM(80, activation='relu', input_shape=(1, 2))) # input_shape=(1 time_step,2 features)

In [ ]:
# Many-to-One Sequence (Single Feature)

X = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,
     36,37,38,39,40,41,42,43,44,45]

y = [6,15,24,33,42,51,60,69,78,87,96,105,114,123,132]

X = X.reshape(15,3,1)

model.add(LSTM(50, activation='relu', input_shape=(3, 1))) # input_shape=(3 time_step,1 features)

In [ ]:
# Many-to-One Sequence (Multiple Feature)

X1  = [3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90,93,
       96,99,102,105,108,111,114,117,120,123,126,129,132,135]

X2  = [5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130,135,
       140,145,150,155,160,165,170,175,180,185,190,195,200,205,210,215,220,225]

y = [24,48,72,96,120,144,168,192,216,240,264,288,312,336,360]

X = np.column_stack((X1, X2))

X = array(X).reshape(15, 3, 2)

model.add(LSTM(50, activation='relu', input_shape=(3, 2))) # input_shape=(3 time_step,2 features)

In [9]:
from numpy import array

data = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

data = data.reshape((1, 10, 1)) # 1 sample,10 time steps, and 1 features

model.add(LSTM(32, input_shape=(10, 1))) # input_shape=(10 time_step, 1 features)

In [10]:

from numpy import array
X = array([[0.1, 1.0],[0.2, 0.9],[0.3, 0.8],[0.4, 0.7],[0.5, 0.6],[0.6, 0.5],[0.7, 0.4],[0.8, 0.3],[0.9, 0.2],[1.0, 0.1]])

# 1 sample with 10 time steps and 2 features.
X = X.reshape(1, 10, 2)

model.add(LSTM(32, input_shape=(10, 2)) # input_shape=(10 time_step, 2 features)

In [ ]:
# The input of the LSTM is always is a 3D array. (batch_size, time_steps, units)

# The output of the LSTM could be a 2D array or 3D array depending upon the return_sequences argument.

# If return_sequence is False, the output is a 2D array. (batch_size, units)

# If return_sequence is True, the output is a 3D array. (batch_size, time_steps, units)

In [12]:
# Example :

# Generated sequences as follows

# One Sample Input Sequence in raw format:
X[0]=[5, 0, 9, 9]

# One Hot Encoding

5 : [0 0 0 0 0 1 0 0 0 0]
0 : [1 0 0 0 0 0 0 0 0 0]
9 : [0 0 0 0 0 0 0 0 0 1]
9 : [0 0 0 0 0 0 0 0 0 1]

# In one_hot_encoded format:  # (1,4,10) (1 Sample ; 4 time steps ; 10 feaures)

X[0]=[[0 0 0 0 0 1 0 0 0 0],
      [1 0 0 0 0 0 0 0 0 0],
      [0 0 0 0 0 0 0 0 0 1],
      [0 0 0 0 0 0 0 0 0 1]]

# Shape of an input to LSTM (X[0].shape):  (1, 4, 10)

In [13]:
# Example 2:

# embedding of the Characters in the string : for LSTM

import numpy as np

word_vec_length = 10 # maximum length of the name

char_to_int = {'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 
               'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 
               'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 
               'w': 22, 'x': 23, 'y': 24, 'z': 25, 'ö': 26, 'ä': 27, 'ü': 28,
               '-': 29, 'ß': 30, ' ': 31}

char_vec_length = len(char_to_int)


# Returns a list of n lists with n = word_vec_length
def name_encoding(name):

    # Encode input data to int, e.g. a->1, z->26
    integer_encoded = [char_to_int[char] for i, char in enumerate(name) if i < word_vec_length]
    
    # Start one-hot-encoding
    onehot_encoded = list()
    
    for value in integer_encoded:
        # create a list of n zeros, where n is equal to the number of accepted characters
        letter = [0 for _ in range(char_vec_length)]
        letter[value] = 1
        onehot_encoded.append(letter)
        
    # Fill up list to the max length. Lists need do have equal length to be able to convert it into an array
    for _ in range(word_vec_length - len(name)):
        onehot_encoded.append([0 for _ in range(char_vec_length)])
        
    return onehot_encoded

names = ['santhosh','anand','sachin','prashanth']

# use asarray to use change the shape of the array which suits for LSTM
enc = np.asarray([np.asarray(name_encoding(name)) for name in names])

print(enc.shape)

# Batch_size(Samples) : 4  : ['santhosh','anand','sachin','prashanth']
# time_step : 10 :  max length of the sentence 
# features : 32 :  Length of the Vocabulary

(4, 10, 32)
