In [18]:
# Our dataset will consist of 15 samples. Each sample will have 3 time-steps where each time-step will 
# consist of a single feature i.e. a number. The output for each sample will be the sum of the numbers 
# in each of the three time-steps. For instance, if our sample contains a sequence 4,5,6 the output will be 4 + 5 + 6 = 10.

In [19]:
import numpy as np
import tensorflow as tf

In [ ]:
# Use Case : Predicts addition of digits(3) 
# ex: (1+2+3) = 6;  (4+5+6) = 15; (7+8+9) = 24

In [20]:
# Creating the Dataset
X = np.array([x+1 for x in range(45)])
print(X)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]


In [21]:
X = X.reshape(15,3,1)
print(X)
#  into 3-dimensional shape with 15 samples, 3 time-steps, and 1 feature

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]

 [[19]
  [20]
  [21]]

 [[22]
  [23]
  [24]]

 [[25]
  [26]
  [27]]

 [[28]
  [29]
  [30]]

 [[31]
  [32]
  [33]]

 [[34]
  [35]
  [36]]

 [[37]
  [38]
  [39]]

 [[40]
  [41]
  [42]]

 [[43]
  [44]
  [45]]]


In [22]:
Y = list()
for x in X:
    Y.append(x.sum())

Y = np.array(Y)
print(Y)

[  6  15  24  33  42  51  60  69  78  87  96 105 114 123 132]


In [23]:
# Solution via Simple LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [27]:
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=0)

In [28]:
test_input =np. array([50,51,52])  #  The actual output should be 50 + 51 + 52 = 153.
test_input = test_input.reshape((1, 3, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[163.57068]]


In [29]:
# We got 150.7 in the output, which is around 3 points less than the actual output value of 153.
# Solution via Stacked LSTM

model = Sequential()
model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=(3, 1)))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(LSTM(25, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=0)

In [30]:
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[153.56308]]


In [31]:
# Solution via Bidirectional LSTM

from tensorflow.keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(3, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [32]:
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=0)

In [33]:
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[154.56036]]
