In [ ]:
'''
Dense layer or Fully Connected Layer


y = mX + b

'''

In [ ]:
import tensorflow as tf
tf.enable_eager_execution()

In [ ]:
import numpy as np

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense,Input

In [4]:
# set some Global Varibales 

input_size = 2
batch_size =10
dense_unit=5

In [5]:
# define input to Model

in_np  = np.random.randint(1,100,size=(batch_size,input_size))

in_np

array([[68,  9],
       [27, 94],
       [70, 22],
       [30, 68],
       [92, 23],
       [73, 23],
       [31, 20],
       [36, 65],
       [ 2, 86],
       [96,  7]])

In [6]:
# Build model using consisting of single Dense Layer

ins = Input(input_size,name='My_input')
out = Dense(dense_unit,use_bias='False',name="my_output")(ins)

model = Model(inputs=ins,outputs=out)

In [7]:
out_np = model.predict(in_np)

In [8]:
out_np

array([[ 23.908571 , -25.157106 , -60.973045 ,  10.42103  ,  11.125078 ],
       [ 50.909958 , -27.232204 ,  -9.702179 ,  59.921234 , -56.656384 ],
       [ 30.444744 , -28.325504 , -60.723167 ,  18.583847 ,   2.8509178],
       [ 39.87445  , -23.308441 , -16.627218 ,  44.096817 , -38.337097 ],
       [ 37.304253 , -36.100018 , -80.756454 ,  20.776003 ,   7.7414074],
       [ 31.775692 , -29.55035  , -63.316414 ,  19.41555  ,   2.9345055],
       [ 18.180618 , -14.500078 , -25.246067 ,  14.557551 ,  -5.665086 ],
       [ 40.24626  , -24.804688 , -22.615908 ,  42.67576  , -34.792942 ],
       [ 39.971405 , -17.088709 ,  11.961746 ,  53.196022 , -57.578083 ],
       [ 31.139887 , -34.427864 , -86.995026 ,  11.192123 ,  19.559725 ]],
      dtype=float32)

In [9]:
out_np.shape   # 10 batches and 5 = Neurons

(10, 5)

In [10]:
# Get all the layesr in the model

In [11]:
model.layers

In [12]:
dense_layer = model.get_layer('my_output')

In [13]:
dense_layer.input

<tf.Tensor 'My_input:0' shape=(?, 2) dtype=float32>

In [14]:
dense_layer.input_shape   # None= bathc_size and 2 = Features

(None, 2)

In [15]:
dense_layer.output

<tf.Tensor 'my_output/Identity:0' shape=(?, 5) dtype=float32>

In [32]:
dense_w = dense_layer.weights[0].numpy()

In [33]:
dense_w.shape

(2, 5)

In [34]:
dense_w

array([[ 0.29097676, -0.34471917, -0.9178967 ,  0.07160282,  0.25299478],
       [ 0.45801687, -0.1906892 ,  0.16043651,  0.6168932 , -0.6753962 ]],
      dtype=float32)

In [35]:
np.matmul(in_np,dense_w)

array([[ 23.90857172, -25.15710652, -60.97304618,  10.4210304 ,
         11.12507892],
       [ 50.9099586 , -27.23220301,  -9.70217854,  59.92123437,
        -56.65638423],
       [ 30.44474459, -28.32550454, -60.72316492,  18.58384728,
          2.85091782],
       [ 39.87445021, -23.30844116, -16.62721789,  44.09682035,
        -38.3370986 ],
       [ 37.30425024, -36.10001552, -80.75645554,  20.77600253,
          7.74140668],
       [ 31.77569175, -29.55035126, -63.31641847,  19.41554892,
          2.93450594],
       [ 18.18061709, -14.50007844, -25.24606711,  14.55755091,
         -5.66508603],
       [ 40.24626017, -24.80468857, -22.61590755,  42.67575777,
        -34.79294133],
       [ 39.97140455, -17.08871007,  11.96174657,  53.19601846,
        -57.57808399],
       [ 31.13988733, -34.42786491, -86.99502647,  11.19212306,
         19.55972505]])

In [ ]:
# output form our model consisting of a single dense layer is simplicity the matrix multiplication of input and weights matrix
# as seen below

In [ ]:
# using Bias


In [36]:

ins = Input(input_size,name='My_input')
out = Dense(dense_unit,use_bias='True',name="my_output")(ins)

model = Model(inputs=ins,outputs=out)

In [37]:
out_np = model.predict(in_np)

In [38]:
out_np

array([[-26.33514   , -38.006035  , -31.740126  ,  21.01604   ,
          9.93193   ],
       [ 59.530945  , -19.875679  , -95.07985   ,  78.657906  ,
         61.227367  ],
       [-17.252941  , -39.797764  , -44.289406  ,  31.536797  ,
         18.291664  ],
       [ 37.938522  , -20.155579  , -72.40363   ,  59.05941   ,
         44.9434    ],
       [-27.252785  , -51.992672  , -52.814564  ,  36.849564  ,
         20.293861  ],
       [-17.948128  , -41.50641   , -46.23964   ,  32.932808  ,
         19.11179   ],
       [  0.29815292, -18.167496  , -28.969324  ,  21.941986  ,
         14.598339  ],
       [ 32.67829   , -23.30828   , -71.74365   ,  57.963554  ,
         43.416233  ],
       [ 65.582146  ,  -5.6546335 , -79.131905  ,  67.28368   ,
         54.604134  ],
       [-41.59521   , -53.35364   , -39.60531   ,  25.232956  ,
         10.406958  ]], dtype=float32)

In [42]:
dense_w = model.weights[0].numpy()
dense_b = model.weights[1].numpy()

In [43]:

# Manully calculating the same
np.matmul(in_np,dense_w) + dense_b

array([[-26.33513892, -38.00603384, -31.74012542,  21.01604009,
          9.93192995],
       [ 59.53094935, -19.87568045, -95.0798468 ,  78.65790379,
         61.22736949],
       [-17.25294185, -39.79776514, -44.28940284,  31.53679633,
         18.29166281],
       [ 37.93852282, -20.15557814, -72.40363252,  59.05940747,
         44.94340312],
       [-27.25278604, -51.99267107, -52.81456399,  36.84956431,
         20.29386008],
       [-17.94812667, -41.50640744, -46.23963958,  32.93280613,
         19.11179036],
       [  0.29815197, -18.16749632, -28.96932381,  21.9419862 ,
         14.59833926],
       [ 32.67829359, -23.30828041, -71.74365211,  57.96355557,
         43.41623342],
       [ 65.58214688,  -5.6546334 , -79.13190424,  67.2836802 ,
         54.60413492],
       [-41.59521234, -53.35364205, -39.60530615,  25.23295617,
         10.40695751]])

In [44]:
# use Bias_initializer

ins = Input(input_size,name='My_input')
out = Dense(dense_unit,use_bias='True',bias_initializer='ones',name="my_output")(ins)

model = Model(inputs=ins,outputs=out)

In [47]:
out_np = model.predict(in_np)

out_np

array([[  4.4803467, -32.224022 , -53.475082 , -45.290302 ,  -5.8059454],
       [-37.375027 ,   2.0455904,  30.50458  , -45.589973 ,  80.65263  ],
       [ -1.0164933, -31.196053 , -47.875732 , -50.62476  ,   5.5924206],
       [-25.615742 ,  -3.5763435,  13.17425  , -39.3972   ,  56.311516 ],
       [  0.9500284, -42.246006 , -66.581085 , -65.00463  ,   1.6493759],
       [ -1.1280375, -32.566887 , -49.938095 , -52.85508  ,   5.84128  ],
       [ -4.4026766, -11.643284 , -14.844753 , -25.062275 ,  12.375376 ],
       [-23.64053  ,  -7.1052513,   6.222126 , -42.298004 ,  52.25554  ],
       [-36.59204  ,  13.521688 ,  47.879414 , -27.107992 ,  78.88238  ],
       [  8.422081 , -46.802883 , -79.13257  , -62.57097  , -13.804968 ]],
      dtype=float32)

In [49]:
# Verify the model output obtaiing following equation

dense_w = model.weights[0].numpy()
dense_b = model.weights[1].numpy()

In [52]:
dense_w

array([[ 0.1093719 , -0.5094273 , -0.8759471 , -0.6394501 , -0.22062653],
       [-0.43966028,  0.15744817,  0.56548035, -0.31196618,  0.9107399 ]],
      dtype=float32)

In [51]:
dense_b

array([1., 1., 1., 1., 1.], dtype=float32)

In [50]:

# Manully calculating the same
np.matmul(in_np,dense_w) + dense_b

array([[  4.48034671, -32.22402346, -53.47508085, -45.29030061,
         -5.80594516],
       [-37.37502509,   2.04559088,  30.50458086, -45.58997297,
         80.65263408],
       [ -1.01649314, -31.19605184, -47.87573051, -50.6247611 ,
          5.59242046],
       [-25.61574209,  -3.57634354,  13.17425036, -39.39720249,
         56.31151712],
       [  0.95002839, -42.24600446, -66.58108675, -65.0046289 ,
          1.64937663],
       [ -1.12803772, -32.56688559, -49.93809152, -52.85507751,
          5.84128076],
       [ -4.4026767 , -11.64328313, -14.84475362, -25.06227589,
         12.37537545],
       [-23.64052984,  -7.10525191,   6.2221266 , -42.29800439,
         52.25553823],
       [-36.59204036,  13.52168822,  47.87941599, -27.1079917 ,
         78.88237822],
       [  8.42208049, -46.80288446, -79.13256085, -62.5709703 ,
        -13.80496788]])

In [53]:
# using Activation Function

ins = Input(input_size,name='My_input')
out = Dense(dense_unit,use_bias='True',bias_initializer='ones',activation='relu',name="my_output")(ins)

model = Model(inputs=ins,outputs=out)

In [54]:
out_np = model.predict(in_np)

out_np

array([[31.759941  ,  0.37922704,  0.        ,  0.        , 29.861065  ],
       [ 0.        ,  8.760498  , 51.437714  ,  0.        ,  0.        ],
       [27.00502   ,  1.4886395 ,  0.        ,  0.        , 25.59734   ],
       [ 0.        ,  6.395734  , 34.54387   ,  0.        ,  0.        ],
       [37.806362  ,  1.1185205 ,  0.        ,  0.        , 35.70222   ],
       [28.094124  ,  1.514641  ,  0.        ,  0.        , 26.62857   ],
       [ 7.9581833 ,  2.1246355 ,  4.6311665 ,  0.        ,  7.775378  ],
       [ 0.        ,  6.005002  , 31.00506   ,  0.        ,  0.        ],
       [ 0.        ,  8.573334  , 53.527607  ,  0.        ,  0.        ],
       [46.96152   ,  0.        ,  0.        ,  0.        , 44.03566   ]],
      dtype=float32)

In [ ]:
# Customizing the weights

we can se the ou own weights are bias of the dense layer.

In [56]:
custom_weights = np.array([[1,2,3,4,5],[6,7,8,9,10]])
custom_bias = np.array([0,0,0,0,0])


ins = Input(input_size,name='My_input')

dense_layer = Dense(dense_unit,use_bias='True',bias_initializer='ones',activation='relu',name="my_output")

out = dense_layer(ins)

model = Model(inputs=ins,outputs=out)

dense_layer.set_weights([custom_weights,custom_bias])

In [57]:
model.predict(in_np)

array([[ 122.,  199.,  276.,  353.,  430.],
       [ 591.,  712.,  833.,  954., 1075.],
       [ 202.,  294.,  386.,  478.,  570.],
       [ 438.,  536.,  634.,  732.,  830.],
       [ 230.,  345.,  460.,  575.,  690.],
       [ 211.,  307.,  403.,  499.,  595.],
       [ 151.,  202.,  253.,  304.,  355.],
       [ 426.,  527.,  628.,  729.,  830.],
       [ 518.,  606.,  694.,  782.,  870.],
       [ 138.,  241.,  344.,  447.,  550.]], dtype=float32)

In [58]:
model.weights

[<tf.Variable 'my_output_4/kernel:0' shape=(2, 5) dtype=float32, numpy=
 array([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]], dtype=float32)>,
 <tf.Variable 'my_output_4/bias:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>]